### ISSUE TITLE
skopeo 404 against nexus oss docker registry

### ISSUE THREAD

**Issue by jaxim** [containers/skopeo#1000]
I am using [nexus oss](https://www.sonatype.com/nexus-repository-oss) (3.25.0-03) to host a private docker registry and have configured it as per the [documentation](https://help.sonatype.com/repomanager3/formats/docker-registry/hosted-repository-for-docker-%28private-registry-for-docker%29).

When I try and use skopeo inspect I am getting a 404 against the image I am trying to query:
```
skopeo inspect docker://mynexus.com/docker-releases/hello-world:linux
FATA[0000] Error parsing image name "docker://mynexus.com/docker-releases/hello-world:linux": error pinging docker registry mynexus.com: invalid status code from registry 404 (Not Found)
```

From the debug I can see its trying to look for v2 at the root level:
```
DEBU[0000] GET https://mynexus.com/v2/
DEBU[0000] Ping https://mynexus.com/v2/ status 404
```

Whereas in the nexus setup, v2 exists after the repository name, e.g:
`mynexus.com/docker-releases/v2`

Is there some config I can use to amend where it is trying to ping?

**Comment by vrothberg** [comment]
Thanks for opening the issue!

Can you ping the registry, or does it work with Docker? My suspicion is that something is off in the setup.

**Comment by jaxim** [comment]
Thanks for getting back to me. I can do a docker pull from my nexus successfully:
`docker pull mynexus.com/docker-releases/hello-world:linux`

Checking my nexus request.log I can see two entries from when I have ran skopeo inspect:
```
[06/Aug/2020:14:06:44 +0000] "GET /v2/ HTTP/1.1" 404 - 1991 1 "Go-http-client/1.1"
[06/Aug/2020:14:06:45 +0000] "GET /v1/_ping HTTP/1.1" 404 - 1991 1 "Go-http-client/1.1"
```

**Comment by mtrmac** [comment]
> From the debug I can see its trying to look for v2 at the root level:
> 
> ```
> DEBU[0000] GET https://mynexus.com/v2/
> DEBU[0000] Ping https://mynexus.com/v2/ status 404
> ```
> 
> Whereas in the nexus setup, v2 exists after the repository name, e.g:
> `mynexus.com/docker-releases/v2`

That’s not how the API (https://github.com/docker/distribution/blob/master/docs/spec/api.md#put-manifest ) works. It is not possible to operate a registry with that protocol that does not use the root namespace on the host name, if only because the image syntax (`docker://mynexus.com/docker-releases/hello-world:linux`) has no way to specify whether the URL to access should be e.g. `mynexus.com/v2/docker-releases/hello-world/manifests/linux` or `mynexus.com/docker-releases/v2/hello-world/manifests/linux`.

Compare the Docker request log; I’m fairly sure you will see a `/v2/` access as well.
