### ISSUE TITLE
"skopeo copy" uses cached layer of different size, causing change in digest

### ISSUE THREAD

**Issue by thomasmckay** [containers/skopeo#1097]
Performing a `skopeo copy --all docker://from:tag docker://to:tag` resulted in a change of digest. After removing `~/.local/share/containers/cache/blob-info-cache-v1.boltdb` the copy maintained digest as expected.
skopeo version 1.2.0
fedora32

**Comment by mtrmac** [comment]
Thanks for your report.

To be explicit, this is intentional behavior; when Skopeo can obtain an “equivalent” representation of the same image based on data that is already present at the destination, and there is nothing to indicate that the specific representation matters (i.e. the destination is not a digested reference, and the image is neither signed nor being signed), the copy implementation prefers quick metadata operations to copying / duplicating large amounts of data.

But for callers that do care about the representation (notably OpenShift which does not always use signatures but records digests separately), it may well make sense to provide an option (especially for `skopeo sync`) to opt in to preserving digests if at all possible, or maybe to option to always preserving digests (or failing if that can’t be done).

**Comment by Jamstah** [comment]
This should be closed by #1520
