### ISSUE TITLE
it's confusing not to  implement the simple `pull` and `push` sub command 

### ISSUE THREAD

**Issue by cooka** [containers/skopeo#1135]
any reason that one has to use such a cumbersome command 
` skopeo copy   docker-daemon:image-name:image-tag  docker://docker.io/image-name:image-tag `
but not just
` skopeo push image-name:image-tag ` 

btw, the fact is docker hub is the de facto DOCKER HUB,
skopeo can keep the prefix, but why not omit it for the default docker hub?

**Comment by rhatdan** [comment]
Podman and Buildah handle the push and pull commands.

The goal with skopeo is to keep it agnostic of the different transports as possible.

**Comment by vrothberg** [comment]
I have low tolerance towards foul language (i.e., "ridiculous).  Please be respectful.

**Comment by mtrmac** [comment]
- There are other opinionated/compatible programs that provide push/pull, both Podman/Buildah, and for this specific command, Fedora/RHEL’s /usr/bin/atomic . Skopeo’s role is basically to be a very thin wrapper over c/image ; there’s ample space for other projects to be more opinionated or high-level.
- I personally find the “push”/“pull” interaction model very confusing to nonsensical for anything but the most direct use: it suggests wasteful and destructive “copies” by push+pull, the need to locally tag first in order to push pointlessly confuses local state and remote locations (should the tag be removed after push? that needs an extra condition; and in the meantime, pulls don’t happen even if others may expect them to). The only reason it seems intuitive is that users have already learned to adapt to this non-obvious design.
- Use of `docker-daemon:` _should_ be cumbersome because it is so expensive; IIRC the above command makes _three_ on-disk copies of all the uncompressed layers of the image, even if all of the image already exists at the destination (unlike both `docker push` and `podman push` from their respective storages, where the operation would be a few roundtrips of metadata checks). Writes to `docker-daemon:` are similarly expensive. It is a last resort for users with legacy infrastructure, not a recommended workflow for newcomers.
- `docker://` _does_ implement the Docker normalization, where `docker://busybox` == `docker://docker.io/library/busybox`. If you mean something else, please provide a reproducer.

**Comment by mtrmac** [comment]
@cooka Are there any unresolved questions? Does the `docker.io` normalization not work as expected?

**Comment by cooka** [comment]
> @cooka Are there any unresolved questions? Does the `docker.io` normalization not work as expected?

It's fine, and I would close this topic, thank you for the work.
