### ISSUE TITLE
Error verifying signature: invalid reference format

### ISSUE THREAD

**Issue by Siddsouza19** [containers/skopeo#1182]
So I wanted to sign an image and verify it using skopeo in a container. To do so I first created a gpg key fingerprint using the steps described here: 

**https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/sect-security_guide-encryption-gpg-creating_gpg_keys_using_the_command_line**

I then ran: 

skopeo copy --dest-tls-verify=false --remove-signatures docker://docker.io/busybox:latest dir:/src/docker_mount/test/busybox:latest

To sign it I ran:

**skopeo standalone-sign /src/docker_mount/busybox:latest/manifest.json /src/docker_mount/busybox:latest FF9CFA884574566A118B214514255E6EE6F2EA0A -o /src/docker_mount/busybox.signature**

Just to reconfirm the fingerprint I used I ran: 

**gpg2 --fingerprint siddhanthd@gmail.com**

To verify the signed image I ran:

**skopeo standalone-verify /src/docker_mount/busybox:latest/manifest.json /src/docker_mount/busybox:latest FF9CFA884574566A118B214514255E6EE6F2EA0A /src/docker_mount/busybox.signature**

That's when I get the error: **FATA[0000] Error verifying signature: invalid reference format**

![skopeo_sign_verify](https://user-images.githubusercontent.com/19501855/106438502-960c5b00-649c-11eb-8345-84a315c90261.png)

Can someone tell me what went wrong?

Also, the next thing I wanted to understand was how to use skopeo standalone-verify on existing redhat images. 

**https://catalog.redhat.com/software/containers/rhel/57ea8cee9c624c035f96f3b3?container-tabs=security**

Above is a link to a redhat linux image. Which has a signing code "**199E2F91FD431D51**" displayed on the website.

![linux_image](https://user-images.githubusercontent.com/19501855/106439707-fea80780-649d-11eb-8a7c-9dc98f5fba2d.png)

How do I use this information to verify the image using skopeo. Even to use the skopeo standalone-verify command I'd need a 40 digit fingerprint, and signature file for image. Can someone share some light on this too? Thank you

**Comment by mtrmac** [comment]
Thanks for your report.

The “docker-reference” parameter to `standalone-sign` and `standalone-verify` is not a path; it’s the signed image identity, something like `registry.mycompany.example/some-repo/busybox:v1.23`.

---

Usually, you shouldn’t be using `standalone-verify` at all; instead, set up a policy using `policy.json`, and use `skopeo copy`, `podman pull` or the like.

If you do need to use `standalone-verify` for some reason, the individual signature files are necessary. The simplest way to obtain them for published images is to set up the sigstores so that Skopeo can find the signatures (see below), and then use `skopeo copy docker://… dir:…`; the signatures will be copied to the destination directory.

---

WRT accessing the Red Hat signatures, see e.g. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/working-with-container-images_building-running-and-managing-containers#defining-the-image-signature-verification-policy_building-running-and-managing-containers .

**Comment by Siddsouza19** [comment]
Thank you for the promt response @mtrmac. I'm gonna try both ways, and post my findings here.

**Comment by Siddsouza19** [comment]
Hey @mtrmac! So I tried what you suggested above with a Red Hat image. And surely after setting the policy.json, and .yaml files right, skopeo copy verified the signatures and only then copied the image along with the signatures to my desired directory. 

![signatures](https://user-images.githubusercontent.com/19501855/106738091-88daa200-663d-11eb-8769-492d57222a80.png)

But my requirement was to verify an image in the registry itself and not copy or pull it. For that I will have to use skopeo standalone-verify. So I ran the following command (I used the signature that got downloaded through skopeo copy in my local directory. I used the fingerprint I found here "https://www.redhat.com/security/data/fd431d51.txt" which is the key used to sign Red Hat images, and that also worked with skopeo copy earlier)

**skopeo standalone-verify /src/docker_mount/ubi:8.0-199/manifest.json docker://registry.access.redhat.com/ubi8/ubi:8.0-199 567E347AD0044ADE55BA8A5F199E2F91FD431D51 /src/docker_mount/ubi:8.0-199/signature-1**

This still gives me the same error: **FATA[0000] Error verifying signature: invalid reference format** 

I then even went on to change the redhat.yaml file to :
**docker:
  registry.access.redhat.com:
    sigstore: file:///src/docker_mount/ubi:8.0-199/**

But skopeo standalone-verify still fails to verify.
![verify_error](https://user-images.githubusercontent.com/19501855/106739291-f804c600-663e-11eb-8763-f70bb5833f16.png)

What am I doing wrong here? How do I get skopeo standalone-verify to work?

**Comment by mtrmac** [comment]
> But my requirement was to verify an image in the registry itself and not copy or pull it.

(Careful: What is your threat model? The registry can change the served image any time, so a point-in-time check is not  useful if the signatures are to project against compromised registries.)


> For that I will have to use skopeo standalone-verify.

(Well, you _can_ use `skopeo copy` to a temporary location and delete that copy. That allows using the full power of `policy.json` without having to reimplement it — especially if you are using `skopeo copy` anyway to get the signature data; the data is being copied anyway, might as well use that to enforce the policy.)

> **skopeo standalone-verify /src/docker_mount/ubi:8.0-199/manifest.json registry.access.redhat.com/ubi8/ubi:8.0-199 567E347AD0044ADE55BA8A5F199E2F91FD431D51 /src/docker_mount/ubi:8.0-199/signature-1**

This looks correct.

> The "invalid reference format" error went. However it lead me to a new error: Error verifying signature: Invalid GPG signature
> 
> ![invalid_gpg_key](https://user-images.githubusercontent.com/19501855/106749577-b4b15400-664c-11eb-8edd-8f4d2f31a4b2.png)

Is the relevant GPG key imported into GPG?

> Also, would you have any idea as to why multiple signatures would get copied for one image?

Because there _are_ multiple signatures, in this case signing various references=identities. (So, `standalone-verify` will only report a match for one of the signatures.)

**Comment by mtrmac** [comment]
Assuming there are no more outstanding questions; if that’s not the case, please reopen.
