### ISSUE TITLE
Current skopeo images in quay registry not available

### ISSUE THREAD

**Issue by DominikWo** [containers/skopeo#1204]
Where can I get the latest Skopeo version as a container image? The quay (v1.2.0) is currently down by at least 2 versions (currently v1.2.2).
Thanks in advance.

**Comment by vrothberg** [comment]
Thanks for reaching out!

I @TomSweeneyRedHat is publishing the images.

**Comment by TomSweeneyRedHat** [comment]
@DominikWo As you noted, I'm a bit behind there.  Updating those images is generally a weekend project for me, but I've pushed it off for several weekends now.  Will do my best to get it done this weekend.  However, v1.2.2 won't be ready until it gets to the stable branch on bohdi, probably a few weeks from now.

**Comment by TomSweeneyRedHat** [comment]
I just double-checked, and the latest available Skopeo version at the moment on Fedora 33 is skopeo v1.2.0.  That's the OS that's used to make these images.  I've checked with the person who controls those rpm's as I expected to see v1.2.1 there.  Once that's up, I'll update the container image.

**Comment by mjgallag** [comment]
@TomSweeneyRedHat shouldn't the testing image that was built 8 hours ago have`skopeo-1.2.2-1.fc33`, see https://src.fedoraproject.org/rpms/skopeo. I'm confused.

**Comment by TomSweeneyRedHat** [comment]
@mjgallag I'm confused too.  The version the `testing:latest` has in it should be equivalent to what you would get if you did this command on a Fedora machine:
```
# dnf -y update  --enablerepo updates-testing skopeo
```
Which should get you to `skopeo 1:1.2.2-1.fc33` now as you noted.  I just double-checked the Dockerfile that we use to make the image, and it looks OK to me.  I'm on PTO today and just popping in/out, I'll look more this weekend.  Thanks for the heads up!

**Comment by mjgallag** [comment]
No rush at all. I wanted the `--format` option of `inspect`. But, I worked around the issue but using `upstream` pinned to a `sha` to avoid potential breakage: `quay.io/skopeo/upstream:latest@sha256:90915fde2466d5163d7ca518cbd2bbcfb45b245ae18131af3f5f01fd8ad23d0e`

**Comment by mjgallag** [comment]
So apparently previous shas are deleted which means you can't peg to them or your code breaks on the next push. I've never seen this before for public images. All my other images are tagged to shas to prevent unexpected breakage since tags are mutable. It's my understanding that this is a widely followed best practice. I can understand the storage requirements to support this may be unsustainable but ideally it would at least be followed for version tags such as `v1.2.0` so one can control when they receive any updates to the image that fall outside of skopeo versioning, such as Fedora updates, to ensure repeatable builds. I see, for example, that if I had used `quay.io/skopeo/stable:v1.2.0@sha256:9b335068de1f4ca63c0d63b32ce631a60dbb9666db9d604caf73bea15319a31a` it would have broken on Feb 24, being replaced with `quay.io/skopeo/stable:v1.2.0@sha256:17ac966aa252ad492c916121682ac49492b755d15fc6cc6aab6ef1be90109e44`. Note that image pulls ignore tag when you have both a tag and sha so the tag is for humans and the sha is what is used for the pull. The idea being that dependabot or myself would notice the new sha and I'd control when I merge it in.

In any case, it looks like Fedora 33 stable has `v1.2.2` now so would be great if we could get a tag. That way at least I can stay pegged to `v1.2.2` if I omit the sha.

Thanks for getting the images updated!

**Comment by TomSweeneyRedHat** [comment]
@mjgallag Thanks for bringing this up.  We recently developed some automated updates of those images in our CI systems.  Previously we had relied on some simple cron jobs and then me remembering to post a "v1.2.0" version tag or what have you.  I think when we made the conversion happen, we might not have considered tromping the shas like that.  @barthy1 thoughts?

**Comment by barthy1** [comment]
@TomSweeneyRedHat for current skopeo image build via Travis, tags should be specified in the code. When skopeo version was bumped (with Fedora version?) tags had to be updated manually [here](https://github.com/containers/skopeo/blob/master/.travis.yml#L14-L15). Requirement about manual update of the tags is mentioned in the release [README](https://github.com/containers/skopeo/tree/master/release#environment-variables).

**Comment by lsm5** [comment]
Closing this... v1.3.1 is available on quay. Please reopen if anything missing.
