### ISSUE TITLE
Skopeo System-testing requires Podman and/or --privileged mode

### ISSUE THREAD

**Issue by cevich** [containers/skopeo#1216]
As part of https://github.com/containers/image/pull/1140 I attempted to enable skopeo's system-tests to run under a Cirrus-CI Docker-based container environment.  This fails horribly due to seccomp differences which are very difficult to resolve.  Skopeo system-testing needs to be re-implemented/updated to operate in a Docker container environment.

The only other alternative I can imagine, is to enable VM-based Cirrus-CI testing for both *skopeo* and *c/image*.  There we can freely use `--privileged` mode to run the old test design, but of course, this also enables kicking that can down the road (i.e. eventually...the tests *do* need to be modernized).

**Comment by cevich** [comment]
(FWIW: I'm leaning toward the VM-based solution)

**Comment by cevich** [comment]
Working on a GCP setup.

**Comment by mtrmac** [comment]
Historically, the tests from Skopeo that c/image _positively relies on_ (that were not migrated from Skopeo to c/image when the two split) are the `test-integration` tests; `test-system` came later, and I wouldn’t be objecting much against just not running them from the c/image setup, if it significantly simplified things. (I don‘t know _that much_ about the use of `test-system`, dropping that from c/image might be dumb. @edsantiago WDYT?)

We _should_ run the `test-system` tests for Skopeo itself, IIRC because they are run during RPM testing and we should avoid downstream surprises.

**Comment by cevich** [comment]
Oh, I didn't realize there was a c/image and c/skopeo split.  Okay, so having a VM-enabled setup for both should address these concerns.  With that in place, I'll be able to replicate essentially what Travis was doing...just without Travis :grin:

**Comment by mtrmac** [comment]
I don’t think there currently _is_ a difference, c/image’s `make test-skopeo` does run both Skopeo’s `test-integration` and `test-system`; I’m just suggesting that it might be possible to make the two differ.

Of course, if we can run all current tests with a VM with no compromises to test coverage, that’s even better.
