### ISSUE TITLE
add policy-verify option - policy and signature verification using signature stores

### ISSUE THREAD

**Issue by dbilling** [containers/skopeo#1306]
While skopeo currently offers a great low-level signature verification option (standalone-verify), it lacks the ability to verify that a container is in policy or not based on the local policy file, and it will not test if a signature is properly accessible in a local or remote signature store as defined by policy.

This proposal is to add a higher level "policy-verify" option to skopeo.  This would be a new command which checks the image for policy compliance.  If the policy indicates a signature is required, policy-verify would also check to ensure the container specified has a valid signature.   Because all the required definitions are in place in the policy file and the registries.d directory, this command would be incredibly simple - only a docker reference would be required as an operand.   Below is an outline of how I would propose the command might work.  Would the maintainers entertain a PR with this feature?  If so I would be happy to make a contribution.

Proposed new command:
% skopeo-policy-verify

NAME
skopeo-policy-verify - Verify an image meets image policy 

SYNOPSIS
skopeo policy-verify  docker-reference 

DESCRIPTION
Verify a signature meets local policy, including signature checks, if defined in policy.

docker-reference A docker reference expected to identify the image

EXAMPLES
$ skopeo policy-verify registry.example.com/example/busybox 
Image meets policy defined in /etc/containers/policy.json

$ skopeo policy-verify registry.disallowed.com/example/busybox 
Image fails policy defined in /etc/containers/policy.json
FATA[0000] Running image docker://hello-world:latest is rejected by policy

$ skopeo policy-verify registry.example.com/example/busybox:nosig 
Image fails policy defined in /etc/containers/policy.json
FATA[0001] A signature was required, but no signature exists

**Comment by mtrmac** [comment]
Thanks for your report.

Checking whether an image on an external registry is correctly signed is fundamentally insecure: the registry can replace the image just after the check, and serve a malicious one instead. Yes, there are situations where doing that is OK, but they are rather rare.

See parts of https://github.com/containers/skopeo/issues/560 discussing this.

**Comment by dbilling** [comment]
Hmm, I was thinking of this as a testing tool, to make sure a policy is configured correctly and the signature store is working.   But yes you are definitely correct that if someone used this as their sole signature verification tool, there is a timing window of substitution risk in whatever time it takes between the policy-verify via skopeo and whatever possible subsequent container consumption that you are worried about that might happen post verification.  

Also, thank you for pointing me to [#560](https://github.com/containers/skopeo/issues/560)  that discussion is helpful, and really clarifies your position.

I do understand your concerns.  However, I still see a tons of of value here for this proposal as a policy and signature store testing tool.   Are there any ideas we could come up that would mitigate your fears of misuse?  Certainly your concern of folks being exposed to timing windows on  signature verification already exist -- they might do skopeo inspect, run the output through manifest-digest, then do standalone-verify, then consume the container in whatever way you are worried they might....   Low and behold, they are subject to the same timing window that you outlined above.

Would you entertain any possible changes to the proposal that might address your concerns?  Maybe one of the following: 

1) Perhaps the output could return the digest that was verified, making it obvious that only this particular digest was verified.
e.g.
skopeo policy-verify registry.example.com/example/busybox:latest
docker://registry.example.com/example/busybox@sha256:90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042 meets policy requirements

2) Clear warnings in the help and man pages of the substitution risk if this is used for verification without consuming by digest.

3) Something else? your idea here?


If your decision is final that this is a no go, that's OK too - that's why I wrote an issue not a PR.   Just want to explore the idea in its entirety before dismissing.       

Thanks for your consideration!

**Comment by mtrmac** [comment]
I think my first instinct is #560 , that this testing software can exist _as part of some larger product_ (which you might be building), that doesn’t make Skopeo the best place. It’s an unquantified best guess, not an immutable brick wall, but changing that opinion would probably require some new arguments/evidence.

It’s fine for a build system to have a “verify the just-built product of a build matches $policy” feature (and it would be very convenient if it automatically referred to the just-built product for the user); it’s fine for a configuration management system / software installer to have a “verify the policy is sane before deploying it” feature (and it would be very convenient if it had a list of images that must be accepted by a “sane” policy and automatically iterated over them for that check).

In both of these cases there’s much more code “somewhere close” than the <50 lines of code it takes to check a remote image against a policy, so those <50 lines can be just inlined into the caller. (I realize that breaks down if the surrounding code is not in Go.) We are trying hard not to break the API, so those 50 lines are hopefully unlikely to break and are, probably, cheap enough to include/maintain — though that’s a vague guess again.

Mostly (but not entirely), Skopeo is a very dumb wrapper for c/image, so it is not going to become a build system, or an installer/configuration management system, with those “very convenient” features suggested above. I’m definitely interested in making the c/image _library_ useful for building such software, but it’s the library where we focus the effort to maintain a stable and generally useful API; the Skopeo command is certainly an API for shell scripts, but only to an extent suitable for building larger complex software systems.

---

WRT alternatives/mitigations:
- 1\. is interesting — especially because the provided digest could really be used to ~safely eliminate future signature checks, that’s a real ~atomic building block for some larger system, while being much easier to use than `standalone-verify` .
 
  A somewhat pedantic objection is that there might be a different policy for …/busybox:latest and a …/busybox@digest ; unlikely to happen in practice but the tool would need to do something about that (probably not _too_ hard but I haven’t thought about it much).

  Overall I think inlining into the larger system as mentioned above is probably better than shelling out to a Skopeo subprocess, if the caller is in Go at least; it’s not that much more code than creating a subprocess, and it can avoid a lot of the overhead (e.g. various configuration can only be read once, instead of once per image).

  There’s ample space for bikeshedding to make the UI less prone to abuse (Name this `skopeo policy-validated-reference` ? Say something like “docker://…@$digest, if referenced using this digest and not a tag, meets policy requirements”?). I don’t know that it would quite satisfy me but at some point I could be overruled by colleagues :)

- 2\. Help/man pages isn’t read when copy&pasting code from a Google search, when under time pressure to “just get things working”.

- 3\. I’m not at all sure this is useful, just some unfinished guesses.

  > Hmm, I was thinking of this as a testing tool, to make sure a policy is configured correctly and the signature store is working. 

  If the goal is just to _write_ `policy.json`+`registries.*`, and make sure it works:
   
  - Nothing tests that better than actual production usage — do a real `podman pull`, deploy a real K8s pod. OTOH that can be very expensive for large images, sure, and changing the configuration on a cluster can be very disruptive.

  - To an extent, shouldn’t this be a feature of the configuration editor? Imagine a `podman image trust set --must-accept=registry.example.com/example/busybox:latest $other_options` that both creates the required configuration verifies it, _before even saving the file to `/etc`_, and only writes it to the production locations if successful. (If it is enough for checking that “policy is configured correctly and the signature store is working” to test a single image)

  If I understand the motivation correctly, the new `podman image trust` option might be pretty close to what you are actually trying to do — it would be less disruptive than modifying production `/etc` only to run Skopeo, and easier to use to manually stage the proposed configuration in a non-production directory only to run Skopeo before publishing to `/etc`.

**Comment by dbilling** [comment]
Just to be clear, in my specific use case, I want to verify that images are available in a registry and properly signed in a signature store.  My use case is on the creation/validation side of things, this verification has no intention of consuming the image, rather it is to prove existence of the image in the repository and to prove it is properly signed in the signature store, so no consumption is required.   Skopeo seemed like the perfect tool to dverify these sorts of things on a remote registry in a very lightweight manner without consuming them.   i.e.  in line with exactly the sorts of things that are already supported in skopeo.  But if you disagree, I will retract the submission.  I agree I can build a private tool that does the things I need.  Was just hoping to share...

As for testing a policy,  that was a secondary benefit for me, but also seemed like a fantastic use of skopeo, you could do it using /etc/containers/policy.json by default as you mentioned, but because skopeo already has the --policy option in place, you could test whatever profile name you felt like using/crafting/editing/playing around with.  Again, a quick easy command line tool just like the current skopeo features...

**Comment by mtrmac** [comment]
Overall the default approach is “inline such a check into a larger automated caller”; the discussed “verify-and-return-a-digested reference” tools or a `podman image trust set --must-accept=` are good to have been captured, but not something we are likely to work on in the immediate future.
