### ISSUE TITLE
make static will err after make shell

### ISSUE THREAD

**Issue by zhangguanzhang** [containers/skopeo#1361]
```
$ make shell
$ make static
make: nix: No such file or directory
make: *** [Makefile:127: static] Error 127
```

**Comment by vast0906** [comment]
install nix  
https://nixos.org/manual/nix/stable/#ch-installing-binary

**Comment by zhangguanzhang** [comment]
> install nix
> https://nixos.org/manual/nix/stable/#ch-installing-binary

```
 sh <(curl -L https://nixos.org/nix/install)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2699  100  2699    0     0   1980      0  0:00:01  0:00:01 --:--:-- 10380
downloading Nix 2.3.13 binary tarball for x86_64-linux from 'https://releases.nixos.org/nix/nix-2.3.13/nix-2.3.13-x86_64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.XjlmTVvvFX'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.7M  100 25.7M    0     0   551k      0  0:00:47  0:00:47 --:--:--  563k
warning: installing Nix as root is not supported by this script!
performing a single-user installation of Nix...
directory /nix does not exist; creating it by running 'mkdir -m 0755 /nix && chown root /nix' using sudo
/tmp/nix-binary-tarball-unpack.XjlmTVvvFX/unpack/nix-2.3.13-x86_64-linux/install: directory /nix exists, but is not writable by you. This could indicate that another user has already performed a single-user installation of Nix on this system. If you wish to enable multi-user support see https://nixos.org/nix/manual/#ssec-multi-user. If you wish to continue with a single-user install for root please run 'chown -R root /nix' as root.
```

**Comment by muzi502** [comment]
> ```
> $ make shell
> $ make static
> make: nix: No such file or directory
> make: *** [Makefile:127: static] Error 127
> ```

Try this way

- Dockerfile

```
FROM nixos/nix:2.3.11 as builder
WORKDIR /build
COPY . .
RUN nix build -f nix
FROM scratch
COPY --from=builder /build/result/bin/skopeo /skopeo
```

- docker build
DOCKER_BUILDKIT=1 docker build -o type=local,dest=$PWD .

**Comment by lsm5** [comment]
does the `/assign` command usually work in this repo? Or is it because @hswong3i is not a member yet or something?

**Comment by mtrmac** [comment]
@lsm5 We don’t currently use the openshift-ci bot on this repo (and regardless of what other benefits it may have, I’m not sure how it would be better than just using the GitHub UI for assignment — this is a bug report, not a PR).

**Comment by lsm5** [comment]
thanks @mtrmac 

@zhangguanzhang so github UI assignment doesn't work either on my side for adding @hswong3i for whatever reason. Maybe retry from your side please?

**Comment by zhangguanzhang** [comment]
> thanks @mtrmac
> 
> @zhangguanzhang so github UI assignment doesn't work either on my side for adding @hswong3i for whatever reason. Maybe retry from your side please?

doesn't work

**Comment by mtrmac** [comment]
Either way I think this traffic has caused enough pings to the contributor in question.

**Comment by hswong3i** [comment]
Due to the messy nix static compile limitation, I had already shift my focus to native DEB/RPM packaging, see https://build.opensuse.org/package/show/home:alvistack/containers-skopeo-1.4.1 for more information.

**Comment by lsm5** [comment]
@hswong3i just a suggestion RE: debian packaging, it would be great if you could help the official debian/ubuntu packager Reinhard Tartler (@siretart) with the official skopeo package itself instead of the OBS fork.

**Comment by hswong3i** [comment]
@lsm5 I don't think official packager could accept my original works due to all of my dirty workaround and simplified implementation for following reason:

- Make it works with kubernetes kubectl/kubeadm/kubelet
  - Currently kubic tool chain couldn't working together with official kubernetes repo (https://v1-17.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) due to conflict of package naming, e.g. kubernetes-cni vs containernetworking-plugins
- Make it works with most (of my) supported OS
  - devel:kubic:libcontainers is just target for non-openSUSE, where openSUSE itself goes to devel:kubic with different behavior 
  - I am looking for a unified behavior from DEB/RPM for simplify my Ansible role implementation, e.g. https://github.com/alvistack/ansible-role-skopeo
- Make it works with multiple legacy release / version
  - Currently only https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.22 coming with multiple release support
  - But I am looking for a way to support both kubectl/kubeadm/kubelet/cri-tools/cri-o with exact kubernetes release, e.g. all in v1.22.x or 1.21.x
  - Moreover, latest kubernetes release is always unstable at the beginning, I always deploy N-1 release for my customer in production environment
  
That's why I even offline vendor all Go dependency into my *.orig.tar.gz for OBS packaging, which violate standard DEB dh-golang packaging style. I couldn't expect @siretart will accept my change request :-(

**Comment by lsm5** [comment]
@vrothberg @mtrmac @zhangguanzhang  If @hswong3i won't be maintaining nix targets in here, do we still need it?

**Comment by rhatdan** [comment]
If @hswong3i can't fix it, then we should drop nix support.
