### ISSUE TITLE
skopeo copy oci-archive fails with missing index.json file.

### ISSUE THREAD

**Issue by bstin** [containers/skopeo#1448]
Hi All. 

Working with this RHEL tutorial (https://www.redhat.com/en/blog/using-rhels-lightweight-kiosk-mode-edge-deployments) but on a Fedora 34 install. 

When running the command:

```
skopeo copy oci-archive:de367fc9-a618-46ad-a52b-658f4d8887a4-commit.tar containers-storage:localhost/kiosk:latest
```

The output is (added `--debug` flag)

```
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is being used 
DEBU[0000] cached value indicated that native-diff is not being used 
INFO[0000] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=true 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]localhost/kiosk:latest" 
FATA[0006] initializing source oci-archive:de367fc9-a618-46ad-a52b-658f4d8887a4-commit.tar:: open /var/tmp/oci131997477/index.json: no such file or directory
```

By searching the [GUID].tar file I confirmed that there is no `index.json` present, so the error makes sense....but I'm at a loss of what do I do to fix this? Can I somehow generate the `index.json` file manually?

**Comment by mtrmac** [comment]
Thanks for your report.

I’d recommend contacting the tutorial authors, or maybe RHEL support if you are a customer. The `index.json` file is an essential part of the `oci-archive:` format, so this seems like something that needs to be fixed in the `composer-cli` input, configuration, or version. (At least https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/composing_a_customized_rhel_system_image/composer-description_composing-a-customized-rhel-system-image#composer-output-formats_composer-description doesn’t suggest anything to do with OCI, but it’s an area I’m unfamiliar with.)

**Comment by lsm5** [comment]
@bstin Closing this, assuming you can get help from the tutorial author / RHEL support.

**Comment by bstin** [comment]
@lsm5 - agreed its not a bug or issue with skopeo.  

For reference for anyone reaching this page via search: The issue is that osbuild-composer does not produce oci-archive tar files on non RHEL machines. So thats why running on Centos / Fedora failed....
