### ISSUE TITLE
is it possible to add a default transport to copy command

### ISSUE THREAD

**Issue by chenzhiwei** [containers/skopeo#1460]
I think most users using copy command to mirror the docker images, are there any special reasons to not adding `docker` as default transport?

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by chenzhiwei** [comment]
I found the dir schema in podman is `dir:/some-dir`, but I think it is better to use `dir:///some-dir`.

**Comment by chenzhiwei** [comment]
Close this issue, seems setting a default transport requires too many changes in the code and the dependencies.

**Comment by mtrmac** [comment]
For the record, I strongly oppose adding any kind of heuristics to `skopeo copy`. `skopeo` is, for the most part, a dumb wrapper around c/image. It is valuable to us to expose _exactly_ the c/image syntax, for testing/reproducing c/image issues without extra environmental influences.

Also, the current `skopeo copy` syntax is deterministic. Consider things like `dir:foo` — is that a `dir:` transport for `./foo`, or a `docker` transport for `docker.io/library/dir:foo` (or, even worse, a `docker` transport for `$one_of_the_search_registries/dir:foo`)? The current syntax, where transports are mandatory, does not have these issues.

And the way the syntax is deterministic makes it easy to wrap `skopeo copy` in shell functions / shell scripts / shell aliases that allow more convenient operation.

---

There certainly is space for tools that wrap c/image in a different CLI uniquely suited at a specific problem, or for tools that aim to provide a large set of commands that work together and use ever-improving heuristics, like Podman.

It _is_ very valuable to have such heuristics and to allow the users to conveniently do whatever they want to do, but when Podman is spending a fair amount of effort on such heuristics and integration, it would be redundant for Skopeo to do the same thing (and it would be even worse if Skopeo ended up using _different_ heuristics).

---

If you are focusing on mirroring container images between registries, the one part of Skopeo that isn’t just a dumb wrapper around c/image is `skopeo sync`, which supports a YAML configuration file that can be written once (and again wrapped in a shell script). We are running into some limitations of the YAML format, and eventually it might be interesting to consider changes to that format to allow specifying _both_ the sources and destinations, so that the user could just say `skopeo sync --yaml foo.yaml` without having to type anything more.

**Comment by chenzhiwei** [comment]
I have a different opinion.

Like adding docker.io or docker.io/library perfix to the nonstandard image name, I think it can improve the user experience by adding the well-known `docker://` to the image where no schema/transport was found.

I went through the code, I know it requires many changes in various places, so I closed this feature request, but this does not mean this feature is unwanted.

**Comment by mtrmac** [comment]
I’m not at all saying tools with such defaults and heuristics shouldn’t exist; if someone wants to maintain one, great. I’m just saying that, at least right now, right now, `skopeo copy` is not such a tool.
