### ISSUE TITLE
Copy statistics

### ISSUE THREAD

**Issue by estahn** [containers/skopeo#1477]
Would it be possible to generate and return statistics on how much data was copied?

**Comment by estahn** [comment]
@mtrmac I'm trying to implement `copy.Image` to see how the `ReportWriter` works.

1. Looking at the snippet below, using `policy := signature.DefaultPolicy(nil)` will result in a sigfault. Any ideas why?
2. Does the `ReportWriter` uses structured information or is it just a stream of string I would need to parse? Given #658 having some sort of stream with the context of metrics and various aggregated views might be useful.

Snippet:
```golang
package main

import (
	"context"
	"os"

	"github.com/containers/image/v5/copy"
	"github.com/containers/image/v5/signature"
	"github.com/containers/image/v5/transports/alltransports"
	"github.com/containers/image/v5/types"
	"github.com/davecgh/go-spew/spew"
)

func main() {
	ctx := context.TODO()
	policy := &signature.Policy{Default: []signature.PolicyRequirement{signature.NewPRInsecureAcceptAnything()}}
	//policy, err := signature.DefaultPolicy(nil)
	policyCtx, _ := signature.NewPolicyContext(policy)
	defer policyCtx.Destroy()

	srcRef, _ := alltransports.ParseImageName("docker://docker.io/library/busybox:latest")
	destRef, _ := alltransports.ParseImageName("dir:/tmp/images")

    spew.Dump(srcRef, destRef)
	spew.Dump(srcRef.Transport().Name())
	spew.Dump(destRef.Transport().Name())
	spew.Dump(policyCtx.Policy)

    srcCtx := &types.SystemContext{
		DockerRegistryUserAgent: "k8s-image-swapper/1.1.0",
	}
	destCtx := &types.SystemContext{
		DockerRegistryUserAgent: "k8s-image-swapper/1.1.0",
	}


	opts := &copy.Options{
		ReportWriter:       os.Stdout,
		SourceCtx:          srcCtx,
		DestinationCtx:     destCtx,
		ImageListSelection: copy.CopyAllImages,
	}

	image, err := copy.Image(ctx, policyCtx, destRef, srcRef, opts)

	spew.Dump(image, err)
}
```

**Comment by mtrmac** [comment]
> @mtrmac I'm trying to implement `copy.Image` to see how the `ReportWriter` works.

I’d expect this should end up integrated in `cmd/skopeo/copy.go`, which does call `copy.Image` already — but experimentation and feedback on the API is of course welcome, and initial experimentation could well be simpler without the whole `cmd/skopeo` infrastructure.

---

> 1. Looking at the snippet below, using `policy := signature.DefaultPolicy(nil)` will result in a sigfault. Any ideas why?

Are you saying `DefaultPolicy` segfaults? I can’t immediately see how that can happen, that’s a bug we should fix. Do you have a backtrace?

A possible rash path is that if `DefaultPolicy` fails with an error, it returns a `nil` policy, and using that `nil` crashes; in that case the caller of `DefaultPolicy` should be handling the error before using the returned policy object.

---

> 2. Does the `ReportWriter` uses structured information or is it just a stream of string I would need to parse? Given [Please provide a basic progress / transfer speed output ("CI compatible") on copy #658](https://github.com/containers/skopeo/issues/658) having some sort of stream with the context of metrics and various aggregated views might be useful.

`ReportWriter` is not what this feature would be built around; in fact we might want to silence it to `io.Discard` so that the standard output, in the `--output=json` mode, doesn’t intersperse JSON and non-JSON output. (Or, alternatively, one of the two would go to a different file descriptor / named file.)

See `copy.Options.ProgressInterval` and `copy.Options.Progress`; https://github.com/cri-o/cri-o/blob/c8bbae9858a084f4244cbd3bb38852d29fc0466b/server/image_pull.go#L173-L211 is an example consumer, just to show the basic structure.
