### ISSUE TITLE
Publish binary releases to GitHub

### ISSUE THREAD

**Issue by jawnsy** [containers/skopeo#1478]
This is an issue to discuss adding binaries to GitHub releases for skopeo. I've had good experience with using goreleaser for this, and since skopeo builds with the regular Go toolchain (e.g. `go install github.com/containers/skopeo/cmd/skopeo@latest` works great), it should be relatively straightforward to add these builds.

Would you accept a pull request to add release builds?

**Comment by rhatdan** [comment]
I think we go through this statically linking idea every year or two. Just 10 days ago we closed.

https://github.com/containers/skopeo/issues/755
https://github.com/containers/skopeo/pull/932
https://github.com/containers/skopeo/pull/670

Please read these issues, before asking any questions.

We prefer distro based versions of the skopeo or to run a containerized version of skopeo from your favorite distro.

podman run quay.io/skopeo/stable:latest ...

We had a nix version which was eventually removed.

**Comment by lsm5** [comment]
@mtrmac podman only releases the linux remote client as a static binary, https://github.com/containers/podman/releases/tag/v3.4.0 . Buildah doesn't publish any static assets https://github.com/containers/podman/releases/tag/v3.4.0 . 

I see a comment in podman's Makefile saying podman doesn't work well w/o CGO_ENABLED, so that's why only the `podman-remote-static` target is built without CGO and published.

@jawnsy If you're signing up to maintain the binary release part going forward and have reasonable certainty of goreleaser not breaking/blocking release, I'm cool with it.

The skopeo Makefile does use a `DISABLE_CGO` variable, but I'd defer to @mtrmac @vrothberg @rhatdan on its impact.

**Comment by mtrmac** [comment]
> I would also appreciate a lot to have static binaries (or pseudo-static binaries that only depend on the glibc[1]), for the following use-cases:
> 
> * teaching (in a short workshop it's easier if folks can download a binary that "just works" rather than wasting 10-15 minutes for everyone to figure out the steps specific to their environments

Don’t the containers serve that purpose, especially in a container-focused course?

> ; especially as there are no packages for Windows for now)

(FWIW with Windows-native, the binary compatibility is probably not an issue, but to my knowledge no-one has worked on making Skopeo a _good_ Windows citizen, e.g. looking for configuration files in the right places.)

> * CI/CD tooling images (it's best if each tool can be installed as a single binary as well, to minimize image size and simplify the maintenance of these images)

Presumably the CI/CD system is not a personal Linux-from-scratch, so can it use a distribution package?

---

> Rather than completely dropping static binary support, would you be OK with having e.g. instructions (perhaps even a Dockerfile or similar) to build a static binary, coming with a big warning informing of the potential issues?

We’ve had that, using various approaches, in the `Makefile`, during most of the history of the project, but they were always replaced (or ultimately removed) after someone noticed, usually after _months_, that the `make` rules don’t actually work. (That’s why the Nix-based last version was removed recently.)

So I think we’re open to a contributor maintaining such build rules, but it’s also, based on how rarely they have been used in the past, not something that warrants us investing extra maintenance effort.

**Comment by mtrmac** [comment]
> That being said, perhaps if someone wants to commit to maintaining static builds, the Skopeo maintainers would be open to merge that for good.

Yes, even without the “commit to” part:

> So I think we’re open to a contributor maintaining such build rules, but it’s also, based on how rarely they have been used in the past, not something that warrants us investing extra maintenance effort.

**Comment by mtrmac** [comment]
… oh, I’m sorry, I have confused “maintaining builds” and “maintaining build _rules_”. We are absolutely fine with including contributed Makefile rules and the like (which is what we had in the past).

I’m reluctant to _officially publish_ static builds (and we never did publish them), because I personally believe _most_ users should not use them, even if they happen to be the easiest option at a first glance; so, not publishing the binaries is a way to nudge users towards a second glance. (For another reason, consider that distribution packages are usually digitally signed using long-term keys that the system _already trusts_, in a way binaries distributed over GitHub or whatever are not; we could have our own keys, and the consumers of the static binaries could, in principle, verify signatures, but frankly most aren’t going to do that, and it’s an extra hassle for everyone.)

**Comment by joaompinto** [comment]
I think you are being overzealous in this policy, and again debating as a general principle about the risk of distributing static binaries.  But well, it's the freedom of Free software.  I will try to publish/maintain the binaries own my own repo.

Thanks for the feedback.

**Comment by vrothberg** [comment]
Thanks everyone for the conversation.  I think we can close the issue.

**Comment by lework** [comment]
I use github action ci to generate binary files.

https://github.com/lework/skopeo-binary/releases

**Comment by willzhang** [comment]
> 我使用 github action ci 生成二进制文件。
> 
> https://github.com/lework/skopeo-binary/releases

in ubuntu 22.04 is work!

**Comment by freemankevin** [comment]
> I use github action ci to generate binary files.
> 
> https://github.com/lework/skopeo-binary/releases

Thank you so much for your work, you saved my problem with source build error on Centos7 with yum install only getting old version.

**Comment by koolay** [comment]
[gorelaser](https://goreleaser.com/) may be help.
