### ISSUE TITLE
how to use  skopeo copy  same as "docker save SOURCE-IMAGE " to  save image to stdout ？

### ISSUE THREAD

**Issue by tanguofu** [containers/skopeo#1485]
we want save docker image to stdout stream inorder to download the image targz by web， just like

`docker save SOURCE-IMAGE | pigz -9 -p 8`

how can i use `skopeo copy`   to do this？

many thanks

**Comment by mtrmac** [comment]
I would expect `skopeo copy docker://… docker-archive:…` to work, in general.

Just using `docker-archive:/dev/stdout` doesn’t work, because that mixes the generated archive with progress information. If the goal is to pipe the output, one way could be to use a named pipe. Or, with a bit of shell, something like
```bash
bin/skopeo copy docker://… docker-archive:/dev/fd/3 3>&1 1>&2 1>&- | tar t 
```
works for me, but the exact syntax is shell-specific.

If this approach fails in some surprising way, please provide an exact reproducer.

**Comment by tanguofu** [comment]
Got it， this is realy amazing shell ！ thanks very much！
