### ISSUE TITLE
Could we extract the content of some blobs copied by scopeo ?

### ISSUE THREAD

**Issue by cmoulliard** [containers/skopeo#1489]
## Question

Is it possible to extract some of the or all the blobs copied by scopeo ?

Blobs have been copied locally using the following command
```
REPO="buildpack-poc"
GRAPH_DRIVER="overlay"
TAG=$(sudo buildah --storage-driver $GRAPH_DRIVER images | awk -v r="$REPO" '$0 ~ r {print $2;}')
IMAGE_ID=$(sudo buildah --storage-driver $GRAPH_DRIVER images | awk -v r="$REPO" '$0 ~ r {print $3;}')
sudo skopeo copy -q containers-storage:$IMAGE_ID oci:$(pwd)/$IMAGE_ID:$TAG > /dev/null 2>&1
```
Next, we need to do something like this to extract the  blob content using info collected from index.json and  manifest
```
cat $IMAGE_ID/index.json
MANIFEST_SHA=$(cat $IMAGE_ID/index.json | jq .manifests[0].digest | cut -d: -f2 | sed 's/.$//')
echo "MANIFEST SHA: $MANIFEST_SHA"

LAST_LAYER_ID=$(cat $IMAGE_ID/blobs/sha256/$MANIFEST_SHA | jq .layers[-1].digest | cut -d: -f2 | sed 's/.$//')
echo "LAST LAYER SHA: $LAST_LAYER_ID"
echo "## Extract the content of the layer containing the package added ..."
tar -vxf $IMAGE_ID/blobs/sha256/$LAST_LAYER_ID
```

Use case: https://github.com/redhat-buildpacks/poc#how-to-get-from-an-image-its-indexjson-manifest-and-digest-files-and-content-of-a-layer

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by mtrmac** [comment]
Thanks for your report.

> Use case: https://github.com/redhat-buildpacks/poc#how-to-get-from-an-image-its-indexjson-manifest-and-digest-files-and-content-of-a-layer

(That’s not really a use case; that’s at best an intermediate step towards doing _something_. Or there’s some context I’m missing about what the purpose of that exercise is.)

---

Skopeo primarily works with images as whole units (so that callers don’t need to care about manifests/layers etc.), and to an extent with the layer blobs as atomic units; it does not really interpret the _contents_ of those blobs, apart from what `containers-storage:` does.

I’m not sure what you are actually trying to do here, but one approach could be to work with the original containers/storage store, either using Podman/Buildah, or maybe the Go API natively: converting the image into a tarball only to extract the tarball _again_ feels to me to be somewhat of a waste.

Or perhaps even working with the c/storage files directly, OTOH a notable downside of that is that the code would have to understand the specific format used by a particular graph driver, if the goal is to only obtain the contents of the _top layer_ and not the whole resulting image (if it is the latter, a `buildah mount` would be much more efficient than anything else).

If the goal is to deal with the contents individually, well, it’s up to you to write code that defines what “deal” means; `skopeo inspect oci:…` can at least list the layers involved, so that can help with manual parsing instead of using `jq`, but actually decompressing/interpreting the tarball is up to whatever code you want to write.

**Comment by cmoulliard** [comment]
> I’m not sure what you are actually trying to do here,

Here is the scenario that we would like to achieve:

For the buildpacks CNCF project we are investigating a way to extend the following application - [Lifecycle](https://github.com/buildpacks/lifecycle) in order during a build to perform the following steps:

- Execute a Dockerfiles top of an image to add new packages, ... (see: https://github.com/redhat-buildpacks/poc/blob/main/bud/bud.go#L40). A new image is created locally and is available under the graph folder path (vfs, overlay, ...)
- Find the newly created layers (without the parent)
- Extract the content of the new layers created to a volume mounted (e.g /extracted)
- The content extracted will be next used by the lifecycle application to build an image for a runtime (Java spring boot, quarkus). As some needed tools are not packaged with the builder image, they will then become available from the `/extracted` volume mounted

**Comment by rhatdan** [comment]
@mtrmac Any update on this?

**Comment by cmoulliard** [comment]
If you are interested, I created a buildah POC supporting the use case I reported. Here is the snippet part where I can find the last layer created and extract the content top of the running container

https://github.com/redhat-buildpacks/poc/blob/9a9687ba2f89b8e39e0747c7e8cd41980b4f8255/buildah/code/main.go#L219-L231

**Comment by vrothberg** [comment]
> If the goal is to deal with the contents individually, well, it’s up to you to write code that defines what “deal” means; skopeo inspect oci:… can at least list the layers involved, so that can help with manual parsing instead of using jq, but actually decompressing/interpreting the tarball is up to whatever code you want to write.

I concur with @mtrmac and think it's out of Skopeo's scope. What would need to be done depends on the individual use case. Should all files be chowned? Should [whiteout files](https://github.com/opencontainers/image-spec/blob/083f635f2b04f7f340685a1e0c4393a0feec3679/layer.md#whiteouts) be ignored or applied to remove existing data?

Other than that, I think it's fairly straight-forward to untar the layer(s) via `jq` and `tar` or as done in the POC.

**Comment by mtrmac** [comment]
> For the buildpacks CNCF project we are investigating a way to extend the following application - [Lifecycle](https://github.com/buildpacks/lifecycle) in order during a build to perform the following steps:
> 
> * Execute a Dockerfiles top of an image to add new packages, ... (see: https://github.com/redhat-buildpacks/poc/blob/main/bud/bud.go#L40). A new image is created locally and is available under the graph folder path (vfs, overlay, ...)
> * Find the newly created layers (without the parent)

As in _possibly multiple_ layers?

> * Extract the content of the new layers created to a volume mounted (e.g /extracted)

Is that content of each layer individually, or the effect of the multiple layers as a single unit?

How do you plan to represent “this layer has deleted a file in the base image” in the extracted data?

> * The content extracted will be next used by the lifecycle application to build an image for a runtime (Java spring boot, quarkus).

Is ”an image” a container image? If so, does this need to extract the contents at all, couldn’t the build process re-use the already created layer blobs without modification?

---

> If you are interested, I created a buildah POC supporting the use case I reported. Here is the snippet part where I can find the last layer created and extract the content top of the running container.

I suspect this could avoid the intermediate OCI step; call `LayerInfos` on the `ref` returned by `storage.Transport.NewStoreReference`, and use `c/storage.Store.Diff`. Besides significantly reducing disk size and overhead (no need to create all the parent layers in OCI format), `Diff` also can create a diff over multiple layers directly.

**Comment by mtrmac** [comment]
Looking at things like https://github.com/redhat-buildpacks/poc/blob/main/buildah/code/main.go , it seems that Skopeo will not be involved in this feature.
