### ISSUE TITLE
Guidelines about how to use Skopeo as a library

### ISSUE THREAD

**Issue by asankov-cb** [containers/skopeo#1490]
We are trying to use `skopeo` as a library. Basically we want to replicate `skopeo inspect` in code and use the result of the command in a programatic way to do something with the data. Bonus - our code is also written in Go.

I have tried finding some official guidelines about this, but was not able to do so. 

I looked at the code and tried to reverse engineer the `inspect` command (https://github.com/containers/skopeo/blob/main/cmd/skopeo/inspect.go) and I think we will be able to basically replicate the few calls that the command is making and achieve what we need, but I was wondering whether there's a "preferred" way to do this or some official guidelines about it.

**Comment by mtrmac** [comment]
Thanks for your report.

Skopeo itself is (apart from `skopeo sync`) a pretty simple wrapper on top of the `github.com/containers/image` library; so I’d recommend just using that library and not worrying about the Skopeo repo, apart from using it as a template.

We do try to have useful c/image reference documentation, but I’m afraid there’s not much in a way of tutorials. Just starting with the Skopeo caller and following the rough sequence of c/image calls it makes is probably a good starting point.

If you have specific questions about the c/image API, please do ask (probably in the c/image repo, so that we can track necessary improvements to the documentation).

**Comment by asankov-cb** [comment]
Thanks for the quick response.

I saw that you are importing a lot of stuff from https://github.com/containers/image but didn't bother to look further into that repo. Now I see that it's meant to use a library and according to the docs it's exactly what we need.

We will start our work and if any issue/ points from improvements arise we will open issues in the https://github.com/containers/skopeo/image repo.

Closing this now.
