### ISSUE TITLE
skopeo sync always try HTTPS first

### ISSUE THREAD

**Issue by mecseid** [containers/skopeo#1519]
With latest skopeo docker image, when I wanted to synchronize my images from Sonatype Nexus to Docker Registry v2, it always tries with HTTPS first, and after it reached the timeout, then fallback to HTTP.

There is any option to use only HTTP?

```
# skopeo --version
skopeo version 1.5.1
```

registries configuration:
```
# cat .config/containers/registries.conf
[[registry]]
location="sonatype-docker-pull.infra-artifact.svc"
insecure=true

[[registry]]
location="registry.infra-artifact.svc"
insecure=true
```

command:
```
for image in $(curl -s http://sonatype-docker-pull.infra-artifact.svc/v2/_catalog | jq .repositories[] | tr -d '"'); do
  skopeo sync \
    --debug \
    --authfile auth.json \
    --src docker \
    --src-tls-verify=false \
    --dest docker \
    --dest-tls-verify=false \
    sonatype-docker-pull.infra-artifact.svc/$image \
    registry.infra-artifact.svc
done
```

sample output from command:
```
INFO[0000] Tag presence check                            imagename=sonatype-docker-pull.infra-artifact.svc/admin-frontend tagged=false
INFO[0000] Getting tags                                  image=sonatype-docker-pull.infra-artifact.svc/admin-frontend
DEBU[0000] Loading registries configuration "/root/.config/containers/registries.conf"
DEBU[0000] Found credentials for sonatype-docker-pull.infra-artifact.svc in credential helper containers-auth.json in file auth.json
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]  No signature storage configuration found for sonatype-docker-pull.infra-artifact.svc/admin-frontend:latest, using built-in default file:///var/lib/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/sonatype-docker-pull.infra-artifact.svc
DEBU[0000] GET https://sonatype-docker-pull.infra-artifact.svc/v2/
DEBU[0030] Ping https://sonatype-docker-pull.infra-artifact.svc/v2/ err Get "https://sonatype-docker-pull.infra-artifact.svc/v2/": dial tcp 10.142.113.212:443: i/o timeout (&url.Error{Op:"Get", URL:"https://sonatype-docker-pull.infra-artifact.svc/v2/", Err:(*net.OpError)(0xc0003dc000)})
DEBU[0030] GET http://sonatype-docker-pull.infra-artifact.svc/v2/
```

**Comment by mtrmac** [comment]
Thanks for your report. This behavior is currently hard-coded; the “try also non-TLS HTTP” and “do not require a trusted certificate and an authenticated connection when using TLS HTTPS” options are both configured using the same `*tls-verify=false`, with no way to choose only one of the two.

It might be possible to use something like `sonatype-docker-pull.infra-artifact.svc:80/$image` ; that will _still_ try HTTPS but if the current one fails because of a weird firewall, using only the exposed port might fail much faster. Do note that this affects all configuration, including credentials — they would need to be set up using the …`:80` name, which is distinct from the port-less one.

**Comment by mecseid** [comment]
Whoops, sorry for late response, and thank you so much for the explanation.
We made some modification, and after that, I could reach it over HTTPS.

So after that, I close the issue.
