### ISSUE TITLE
copy: consider support cosign: verify image while pulling from source & sign image while copying to destination

### ISSUE THREAD

**Issue by Dentrax** [containers/skopeo#1533]
Currently, we can pass a `--sign-by` flag by giving a GPG key.

```
--sign-by FINGERPRINT                   Sign the image using a GPG key with the specified FINGERPRINT
```

Just thinking how [cosign](https://github.com/sigstore/cosign) fit in this project, so drew the following architecture:

![skopeo-crane-cosign](https://user-images.githubusercontent.com/16493751/147941257-02265efc-aa5f-4826-906a-28b0189d0ec7.png)

We probably have to introduce some new flags to achieve this goal:

```
--dest-public-key <PATH TO PUBLIC KEY for SOURCE>
--src-private-key <PATH TO PRIVATE KEY for DESTINATION>
--sign-by <GPG,COSING> # to make it backward compatible
```

Eventually, the final `copy` command will look like this:

```
$ skopeo copy docker://src/foo:1.0 docker://dest/foo:1.0 --sign-by cosign --dest-public-key </path/to/public.key> --src-private-key </path/to/private.key>
```

It's optional to sign the image again with a different key. The motivation behind this is we might want to ensure all the images are signed with our own private key in the internal registry. So we can easily validate it before the deployment.

Any thoughts?

cc @developer-guy @dlorenc

**Comment by mtrmac** [comment]
Thanks for your report.

Most of that infrastructure needs to be developed in containers/image (and in particular, the public keys or other roots of trust need to be configured in `policy.json`, so that users are secure without having to provide them manually on every single command and never forgetting). Only after it is implemented and designed there would we discuss the details of how to expose it in a Skopeo UI.

For reference, some very partial work on that has happened in https://github.com/containers/image/pull/1364 .

**Comment by vrothberg** [comment]
@mtrmac and I are currently working on integrating cosign into the toolchain.

**Comment by developer-guy** [comment]
that's awesome, please let us know if anything we can help 🙋🏻‍♂️

**Comment by developer-guy** [comment]
@vrothberg @mtrmac, is there anything that we might get involved in it? We're willing to work on this 🤩

**Comment by vrothberg** [comment]
> @vrothberg @mtrmac, is there anything that we might get involved in it? We're willing to work on this star_struck

Thanks for offering help, @developer-guy, much appreciated!  At the time of writing, I don't see any work items that we can distribute.  We are currently consolidating parts of sigstore/cosign into sigstore/sigstore; the cosign code entails a lot dependencies that we need to prune.

**Comment by Dentrax** [comment]
> the cosign code entails a lot dependencies that we need to prune

Maybe we can just do call cosign binary directly instead of bring it as a new dependency.

**Comment by vrothberg** [comment]
> > the cosign code entails a lot dependencies that we need to prune
> 
> Maybe we can just do call cosign binary directly instead of bring it as a new dependency.

I don't think that is sustainable solution long term. The binary size of Skopeo is currently ~20MB, Cosign is currently at ~90MB. Cosign can do much more than just signing and verifying images.

**Comment by Dentrax** [comment]
Dropping [Sanitize cosign's dependency tree](https://github.com/sigstore/cosign/issues/1462) issue as a reference.

**Comment by mtrmac** [comment]
To update the status, as of #1701 and the just-released Skopeo 1.9.0, Skopeo can enforce signatures via `policy.json`, and create new signatures on copy; both _only_ using public/private key pairs, with no Fulcio/Rekor features.

**Comment by Dentrax** [comment]
> It seems like the assumption here is that we want to establish trust on a copy operation.

Yes, this is the idea, but also I see the your concern in next statement:

> Talking to users and customers taught me that they don't want to trust the machine / registry that's doing the copy but rather the source.

Miloslav already covers the exact use-case and why we need:

> some large companies like to have an internal “use in $company's approved” signature added to every third-party image, and enforce their presence.

Definitely what we were looking for!

---


I tried the new v1.9.0 release and couldn't make it work in the first place and filed an issue: https://github.com/containers/image/issues/1613

After played a while, I am finally figured it out and make it work!

This feature is exactly why we filed this issue is for. I think we can close this one. 👏

**Comment by Dentrax** [comment]
> why would someone do that with skopeo as part of the copy?

Calling cosign binary right after copy of an image, leads to a slight time window in which it could have tampered. I think signing should be inherent to the image copy process.

One use-case example is that companies runs tons of images in the production. If you want to enforce signed image policy in your clusters using a Policy Engine, you have to find all the public keys to verify against with. Instead we could mark the image simply one signature to ensure: "yes, we copied that image and validated it's signature, we trust this image to run in clusters. (Its could be scanned, audited, etc.) 

> Do we really want to carry all that into skopeo?

I completely understand the concern here. We don't want to make `skopeo` an _image signing tool_ by adding bunch of features. So we should be careful here.

**Comment by dmesser** [comment]
I get the argument that currently the gap in `cosign` to sign local images is a problem from a security point of view. However the use case where this is important IMHO is not where `skopeo copy` would be used but where the image is built locally, tested, attested to and then signed ideally _before_ pushed to a registry.

In your example @mtrmac you speak about an internal testing repo. So `cosgin` could totally be used to sign that image but not upload the signature (`--upload=false`) and then push the signature and image to the target registry. I appreciate the correctness of `skopeo copy` in relying on the digest, same as `cosign`. 
But it the latter has way more options that the limited support of `skopeo`'s `--sign-by-sigstore-private-key`, e.g. KMS which is likely in place in larger environments because local file-based key management is extremely cumbersome. I would expect the majority of users to rely on that rather on `skopeo` with likely outdated imports of cosign. Hence I am wondering why even accept all the maintainer responsibility to keep `cosign` support updates and all the troubles that come with this heavy-weight import. But I can also see how you would need to do that anyway for the verification part of images signed in Sigstore style (which I would still +1), so I guess I can rest my case 😄 

@Dentrax This interesting, because I heard exactly the opposite. In a zero-trust environment customers don't want to trust the machine that does the copy. They want all the images to be signed by the vendor already and trust the vendors keys for full end2end accountability and integrity. I think cosign's effort to move towards OIDC identity based trust

**Comment by mtrmac** [comment]
> However the use case where this is important IMHO is not where `skopeo copy` would be used but where the image is built locally, tested, attested to and then signed ideally _before_ pushed to a registry.

That’s just not how it works in the GitHub.com/containers ecosystem. Locally-built images in c/storage don’t have a compressed representation that can be signed and then pushed; they are compressed _during_ the push, and that’s the earliest reasonable time to sign them (before that, an uncompressed representation would be signed, and it would have to also be published uncompressed in order not to break the signature).

Sure, there’s _some_ nuance to this (a single-purpose local registry, or pushing to a staging `dir:` with compression), but the base case most users should be thinking about is “build an image, and sign as a part of the first push to a registry”. Experts to signing and attestation might have a different design but they would also know why they want to deviate from the base case.

---

> But it the latter has way more options that the limited support of `skopeo`'s `--sign-by-sigstore-private-key`, e.g. KMS which is likely in place in larger environments because local file-based key management is extremely cumbersome. I would expect the majority of users to rely on that rather on `skopeo` with likely outdated imports of cosign.

(Again, I expect the majority of users to rely on Podman rather than Skopeo, which makes all this focus on Skopeo a bit surprising.)

> Hence I am wondering why even accept all the maintainer responsibility to keep `cosign` support updates and all the troubles that come with this heavy-weight import.

\*shrug\* The software exists. I don’t see arguing _now_ that it shouldn’t have been written as all that productive.

- We need a signing workflow that is simple to understand and secure by default. I argue that `podman push --sign-by`, and `skopeo copy`, can be that workflow; `cosign sign` seems to be one but in practice almost never is (because the registry becomes a risk, and because the simplest way to use it exposes an _unsigned_ image to users, causing a disruption to consumers that enforce signatures). Of course that could be fixed in Cosign.
- “Outdated imports of cosign” are not really a concern. First, the signatures are a long-term artifact and they must be stable over time. WRT keeping up with security vulnerabilities, the much smaller scale actually makes that much more manageable.
- The scope of support/maintenance any team, or vendor, is always smaller than the whole universe of software that exists. The alternative of Podman somehow fully supporting all 80 MB of `/usr/bin/cosign`, and all the features that will ever be added, _just isn’t what would happen_. There will certainly be users that will want to use `/usr/bin/cosign` directly, rather than Podman, and we’re perfectly fine with that.

Specific RFEs and pointing out functionality that is critical to support (both for signing and verification) could be useful (in separate issues, in the c/image/ repo, please). “This feature shouldn’t exist” is much less so.

**Comment by mtrmac** [comment]
> @Dentrax This interesting, because I heard exactly the opposite. In a zero-trust environment customers don't want to trust the machine that does the copy. They want all the images to be signed by the vendor already and trust the vendors keys for full end2end accountability and integrity.

`policy.json` allows users (if they want to take all that extra effort) to have both.

**Comment by dmesser** [comment]
To be honest I didn't know that skopeo had the `sign-by` variant for SigStore style signature until today. I assumed it was in the works but it seems like this issue hasn't been updated with that progress. So yeah, it's a moot point now.

For what it's worth, since `cosign` signs the digest it can't currently not sign before it is in the registry, for the reasons you say. So I guess what podman/skopeo are doing is simply cutting the time where an unsigned image exists in the registry down vs. the time it takes for a pipeline to run podman/skopeo and then cosign. Let me know if this understanding is incorrect. The thinking on the cosign side seems to go towards a solution that uses a local OCI layout for this: https://github.com/sigstore/cosign/issues/596#issuecomment-1196612492

**Comment by mtrmac** [comment]
> So I guess what podman/skopeo are doing is simply cutting the time where an unsigned image exists in the registry down vs. the time it takes for a pipeline to run podman/skopeo and then cosign. 

Thanks, that’s actually a good point: the c/image/docker destination implementation does write the manifest before the signatures, so there _is_ a time where the image is visible on the destination unsigned. But that’s not actually inherent to the design, let’s track fixing it in https://github.com/containers/image/issues/1623 .

**Comment by mtrmac** [comment]
The last update for this issue is https://github.com/containers/skopeo/issues/1533#issuecomment-1187450780 .

**Comment by mtrmac** [comment]
Skopeo 1.11 now supports
- Creating signatures using Fulcio-generated certificates
- Uploading created signatures to Rekor
- In `policy.json`, enforcing Rekor log presence (off-line only, based on a SET in the signature)
- In `policy.json` accepting Fulcio-generated certificates (with a _very_ restricted issuer/subject matching capability).

That’s about as far as I currently want to take this; any future enhancements would depend on user feedback and production experience. (#1704 is still mostly outstanding.)
