### ISSUE TITLE
Getting access to local registry

### ISSUE THREAD

**Issue by jeusdi** [containers/skopeo#1537]
I'm running a local registry. I'm able to reach it getting repositories:

```
$ curl -s -i -X GET http://registry.localhost:5000/v2/_catalog
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
Date: Sun, 09 Jan 2022 21:55:43 GMT
Content-Length: 65

{"repositories":["arxius-solr","arxius-zookeeper","fhir-mongo"]}
```

As you can see, I'm getting:

```json
{
  "repositories": [
    "arxius-solr",
    "arxius-zookeeper",
    "fhir-mongo"
  ]
}
```

I'm trying to inspect my local registry running at registry.localhost:5000. Nevertheless, I'm getting:

```
$ skopeo inspect --no-creds docker://registry.localhost:5000
ERRO[0000] The storage 'driver' option must be set in /etc/containers/storage.conf, guarantee proper operation. 
FATA[0001] Error parsing image name "docker://registry.localhost:5000": reading manifest 5000 in docker.io/library/registry.localhost: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

Two question here:

1. Why is it getting me that I need authention when using `curl` it's not requesting credentials?
2. What's first error, `ERRO[0000] The storage...`?

**Comment by vrothberg** [comment]
Thanks for reaching out and for providing the details.

> Two question here:
> 
>     1. Why is it getting me that I need authention when using `curl` it's not requesting credentials?

While the registry runs at `registry.localhost:5000` it's not a fully-qualified image reference since no namespace or image name are specified. Hence, Skopeo normalized the references with docker.io to `docker.io/library/registry.localhost`. The error doesn't come from your local registry but from docker.io.

A valid reference would, for instance, be `registry.localhost:5000/repo/image:tag` 

>     2. What's first error, `ERRO[0000] The storage...`?

It looks like your /etc/containers/storage.conf does not specify a driver. In case you want to copy from or to the `containers-storage`, it is recommended to specify one.
