### ISSUE TITLE
Preserving image digests when using sync command between public registries and AWS ECR

### ISSUE THREAD

**Issue by stevejr** [containers/skopeo#1579]
I am using the sync command with public registries (quay, docker hub etc) to sync images to a private AWS ECR account. When syncing a multi-arch image, for example `quay.io/jetstack/cert-manager-webhook:v1.6.1` I can see that the manifest is created in ECR with the correct tag and then 5 `untagged` images are created. However, the digests of the images in ECR are different to the digests in the original image manifest. Is this correct when using the `--preserve-digests` flag?

This is the command I am running:

```
skopeo sync --src yaml --dest docker --all --preserve-digests images/sync.yaml <account>.dkr.ecr.eu-west-1.amazonaws.com 
```

This is the sync.yaml file:

```
quay.io:
  images:
    "jetstack/cert-manager-webhook":
      - "v1.6.1"
```

If I do a `docker manifest inspect quay.io/jetstack/cert-manager-controller:v1.6.1` I get 5 entries and I expected that the digests should match those of the untagged images in ECR. I can see that the digest of the manifest is preserved. 

Is it only the manifest digest that should be preserved?

**Comment by mtrmac** [comment]
Thanks for your report. That’s doesn’t immediately look expected, though
>  I can see that the digest of the manifest is preserved.

Assuming you mean the digest of the _top-level manifest list_ is preserved, that immediately means that the digests of the per-arch images are also the same. So that would suggest some unrelated tooling problem or misunderstanding.

Can you provide the output of `skopeo inspect --raw`, for both the top-level manifest lists, and at least one of the per-arch images that differs in digest (i.e. the source-registry and destination-registry variants, for the same arch), please? As well as the sha256 values (`skopeo inspect --raw  docker://… | sha256sum`) of each.

**Comment by stevejr** [comment]
Ok, have double checked it again and it could be user error on my side as the digests look the same. I think I must have misread the manifest/images I was pushing into ECR.

**Comment by stevejr** [comment]
@mtrmac - Another question - is there a way to preserve the full repository name when pushing to ECR? So for `jetstack/cert-manager-controller` it gets pushed into a repo without the `jetstack` prefix. 

Can we keep the prefix? I tried the `--scoped` flag but that also inserted the registry name i.e. `quay.io`

**Comment by mtrmac** [comment]
See the “Synchronizing to a container registry keeping the repository” example in the man page.

**Comment by stevejr** [comment]
Thanks. Closing issue.
