### ISSUE TITLE
"size" is displayed blank after copying image to harbor registry

### ISSUE THREAD

**Issue by mehulgogri** [containers/skopeo#1624]
I am trying to copy one of the docker images from k8s.gcr.io into my internal harbor registry using skopeo push command and the size of this image on the harbor registry UI is displayed blank.

`skopeo copy --src-tls-verify=false --dest-tls-verify=false docker://k8s.gcr.io/volume-nfs:0.8 docker://harbor-registry/k8s.gcr.io/volume-nfs:0.8`

When I try to pull this image it is downloaded properly and of the exact size.

I tried to do the same using docker push and the image size is displayed correctly on the harbor registry UI.

What is happening in the skopeo copy that is making the size displayed as blank?

Does skopeo support copy images from the Jfrog registry to the harbor registry?

**Comment by mehulgogri** [comment]
looks like manifest file is getting corrupted because k8s.gcr.io/volume-nfs:0.8 image is 5 years old and skopeo is unable to support this older manifest file?

**Comment by mehulgogri** [comment]
`schemaVersion` in this older manifest is 1 and `skopeo copy` is not converting it to 2 whereas `docker pull` does convert this `schemaVersion` to 2

WORKAROUND: first `docker pull` this image locally and then push it into registry using `skopeo copy`

**Comment by mtrmac** [comment]
Thanks for your report.

Yes, this is likely to be because of schema1. That format does not include size of layers in the metadata. (In principle, the registry of course has access to the layers, so nothing prevents it from looking up the sizes in its own records, and displaying _that_ in the UI; so, I think it’s reasonable to view this as a possible missing registry feature, albeit one that is getting less likely to be added over time, as schema1 getting more and more obsolete.)

`skopeo copy` defaults to preserving the original format, which is the conservative choice, the only way to preserve digest references, and the choice most likely to allow reusing the image data across other copies / other images. If you want to force a conversion to schema2, you can use `skopeo copy --format=v2s2`.
