### ISSUE TITLE
Can Skopeo Be Used to Sign and Then Verify a Local Image?

### ISSUE THREAD

**Issue by adammfrank** [containers/skopeo#1628]
Usecase:

I want to be able to 
1. Sign and push a docker image to a repository
2. Pull and verify the image's signature
3. Copy the signed image, and it's public key, and transport it to another machine without using a public registry (air-gapped)
4. Verify the image on that air-gapped machine, and run it

Is this possible? If so could I please have some guidance? I'm having a lot of trouble understanding what I would need to do.

Sorry this is vague.

**Comment by mtrmac** [comment]
Thanks for your report.

The thing that is signed is a specific image _representation_. So, it is not possible to ”pull” the image in the traditional sense (extract the compressed image data into individual uncompressed files) in a way that allows recreating the original representation (primarily because re-compressing is not deterministic enough) in a way that would allow it to have an on-registry representation with a valid signature.

However, it is possible to copy the original representation as is.

One approach is to use a temporary registry: in 2., run a registry (perhaps as a container, with a volume pointing to some out-of-container directory), copy the image there (`skopeo copy docker://$source docker://$temporary` or `skopeo sync`; with appropriate sigstore configurations for both of the registries, so that signatures are also copied); then copy that backing volume + the signatures across the air gap, again run a temporary registry, and copy from that temporary registry to the destination. This is the approach I generally recommend, because using a registry allows reusing layer data across images (e.g. the shared base image is only effectively copied once).

Another approach is to use the `dir:` transport:
```sh
skopeo copy docker://$source dir:temp-dir
# copy temp-dir across the air gap
skopeo copy dir:temp-dir-copy docker://$destination
```
or the equivalent `skopeo sync` functionality. That doesn’t require a temporary registry (and doesn’t require a temporary sigstore to go along with the registry), but it doesn’t reuse layer dat across images.

For 4., the signatures contain the image identity, i.e. a `$source` signature won’t match when trying to `podman pull $destination`. One way to design this is to continue to use `$source` names in all configuration, and use `registries.conf` mirror functionality to transparently redirect `$source` accesses to the `$destination` mirror; another is to use `policy.json`’s `remapIdentity` functionality so that the `$source` signature matches for `$destination` images.

**Comment by mtrmac** [comment]
Please reopen if there are any more questions.

**Comment by omkhard** [comment]
Hi ,
I was trying `skopeo standalone-verify`  to verify the signed image on the other docker registry for an airgap scenario,  but error comes :

root@server:$PWD# skopeo standalone-verify manifest.json HARBOR_B/harborrel/debian:9 $(cat fingerprint) signature
FATA[0000] Error verifying signature: Docker reference HARBOR_A/harborrel/debian:9 does not match HARBOR_B/harborrel/debian:9


I have signed the image on HARBOR_A docker instance , and I copied the image using `skopeo copy` to HARBOR_B docker instance.

Is there any solution to map HARBOR_A to HARBOR_B , i got to know about configuring policy.json , but there is not much documentation on it for this scenario.

**Comment by mtrmac** [comment]
1. Most importantly, checking whether a signature is valid “on a registry” does not protect against a malicious registry. Signatures must be verified during image pull / use.
2. For the `standalone-verify` command (which I would expect to be very rarely used in production scenarios), the expected reference is literally in on the command line. Just change it. (`standalone-verify` is a low-level ~debugging tool, so it doesn’t make much sense to make that more indirect.)
3. For production use with `policy.json`, see `remapIdentity` or perhaps `exactRepository`/`exactReference`; https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md contains several examples.
