### ISSUE TITLE
--dest-compress _silently_ ignored for docker-archive:

### ISSUE THREAD

**Issue by ecki** [containers/skopeo#1677]
When i use copy (from "`docker:`") to `docker-archive:/tmp/image.tgz --dest-compress` Skopeo always seems to write a uncompressed TAR file. Specifying the --dest-compress or a .tgz file ending seems to not help. Is that the expected behavior? On the opposite direction skopeo seems to start with detecting if the archive is compressed.

(no that i write the bug report, I think i specified the --dest-compress after the destinaton argument, maybe thats the problem - in that case it should probably warn me about ignored options?)

**Comment by mtrmac** [comment]
Thanks for your report.

The `--dest-compress` parameter is documented to only affect the `dir:` transport.

The `docker-archive:` transport doesn’t provide any feature to compress the created file. It is, of course, possible to compress it manually afterwards, or to use
```sh
skopeo copy --quiet $source docker-archive:/dev/stdout | gzip > ….tar.gz
```
(in that case, note that the `--quiet` option is required so that `/dev/stdout` doesn’t contain _both_ the archive and progress messages).

---

It’s certainly worth considering to warn, or reject, options that can’t affect the chosen transport. Historically Skopeo is completely naive about that, it passes all individual options, and the transport:image text, to the underlying library.

**Comment by ecki** [comment]
I think that restriction is fine (and I saw the Limitation to the dir transport). Maybe add it to the man page “docker archives will be created as uncompressed tar files”.

**Comment by ecki** [comment]
Ah sorry you renamed it..
