### ISSUE TITLE
Digest changed while skopeo copy

### ISSUE THREAD

**Issue by myifeng** [containers/skopeo#1720]
I tried to copy the image, but the digest of the target is not consistent with the source image

``` shell
docker run quay.io/skopeo/stable:latest copy --preserve-digests docker://quay.io/skopeo/stable:latest docker://my-repo/quay.io_skopeo_stable
Getting image source signatures
Copying blob sha256:ca576d37904fd447f2bed3c0df4014a39f47f8b77017c1fef26de354a5c300aa
Copying blob sha256:62946078034b7fe37984579d9b82ccf20cc98ffcd6517cf79ffad18e06fe2b23
Copying blob sha256:c43e9a6048c94d957f961a484f4c370eb1d9f1d8b17766f955ed5b569213bf09
Copying blob sha256:4e4874c8331f05ee2c0bda83c844076ebf27e200fd86a3c65991e192d8af9d50
Copying blob sha256:54307fc82dcc27c4a726427da43131b4dd7671777318cb0dd8c71d1673d588cb
Copying config sha256:861250320cddbafaf9e4485c9b453b71b39f2898025ed8d37d8a5fef6adda45d
Writing manifest to image destination
Storing signatures
```

`quay.io/skopeo/stable:latest` : `Digest: sha256:c959266533280bd246cf33dd90cfbe6a4708b7883178d18531ff3e8a2be7f118`
`my-repo/quay.io_skopeo_stable` : `Digest: sha256:33e72c056f95aac1983ac71dad1c584dc5c5f69223a4f8b8b34ebbbb9ba45e99`

**Comment by mtrmac** [comment]
Thanks for your report. c959… is the digest of the multi-arch manifest; the copy only copied the image for the current architecture, 33e7… is the amd64 per-architecture image.

So this is currently behaving as expected; you can use `--all` to copy all architectures.

I can see how that can be quite surprising.

It’s tempting to suggest that `--preserve-digests` should imply `--all` — on balance I don’t think it’s worth it because there are RFEs to e.g. only copy some architectures and the like, and preserving individual images while possibly editing the top-level manifest might be useful, and always implying `--all` would not be desirable in that case. Also I’d find it surprising if `--preserve-digests` so significantly changed the behavior of a copy operation. Others might well have another opinion on this.

At the very least, the man pages should point at `--all` for `--preserve-digests`.

**Comment by rhatdan** [comment]
I think the defaults are fine, but adding documentation on --all with --preserve-digests should be done.

**Comment by myifeng** [comment]
> 

That's right, it solved the problem perfectly.

**Comment by myifeng** [comment]
> Thanks for your report. c959… is the digest of the multi-arch manifest; the copy only copied the image for the current architecture, 33e7… is the amd64 per-architecture image.
> 
> So this is currently behaving as expected; you can use `--all` to copy all architectures.
> 
> I can see how that can be quite surprising.
> 
> It’s tempting to suggest that `--preserve-digests` should imply `--all` — on balance I don’t think it’s worth it because there are RFEs to e.g. only copy some architectures and the like, and preserving individual images while possibly editing the top-level manifest might be useful, and always implying `--all` would not be desirable in that case. Also I’d find it surprising if `--preserve-digests` so significantly changed the behavior of a copy operation. Others might well have another opinion on this.
> 
> At the very least, the man pages should point at `--all` for `--preserve-digests`.

That's right, it solved the problem perfectly.

**Comment by rhatdan** [comment]
Care to open a PR?
