### ISSUE TITLE
"skopeo sync --src yaml" with "images-by-tag-regex" ignore invalid tag format

### ISSUE THREAD

**Issue by polobread** [containers/skopeo#1740]
Hi skopeo team,

I use skopeo sync from the docker repo of another team own to AWS ECR. The docker repo includes a little invalid tags, but I do not have any permission to fix those. I think command "skopeo sync" could change to ignore invalid tags, show warning and continue. Not break. 

the error message:
```
$ skopeo sync --src yaml --dest docker  --dest-creds 'AWS:xxx' ./image-sync.yaml 123.dkr.ecr.rrr.amazonaws.com

ERRO[0000] Error creating a reference for repository xxx.docker.server/aaa/bbb and tag "sha256:16077473b14e14e5662d1499b777feea6faf21aa361e3e03cb90cc30e3cb71b2": invalid tag format 
```

my image-sync.yaml as below
```
"xxx.docker.server":
    images-by-tag-regex:
      aaa/bbb: ^(latest|\d+\.\d+)$
```

the tags of docker repo
```
$ skopeo list-tags "docker://xxx.docker.server/aaa/bbb"
{
    "Repository": "xxx.docker.server/aaa/bbb",
    "Tags": [
        "1.10",
        ...
        "latest",
        "sha256:16077473b14e14e5662d1499b777feea6faf21aa361e3e03cb90cc30e3cb71b2",
        "sha256:86d403941a4f062bbd12e50d6f7898bf5cc84916d7a6052f7a4a3fe26fcef1dd"
    ]
}
```

Thanks

**Comment by vrothberg** [comment]
Thanks for reaching out, @polobread.

Did you consider using the `skopeo sync --keep-going`?  `--keep-going` will instruct skopeo to not return on errors.

**Comment by polobread** [comment]
Hi vrothberg,

I have tried `skopeo sync --keep-going` , but it does not support ignore this error.
As I know, the flow is fetch tags / validation tags (this step can not ignore) / copy image (with keep going).

validation tags
https://github.com/containers/skopeo/blob/main/cmd/skopeo/sync.go#L247

```
--keep-going If any errors occur during copying of images, those errors are logged and the process continues syncing rest of the images and finally fails at the end.
```

**Comment by vrothberg** [comment]
Thanks for pointing that out, @polobread!

Probably we should move tag validation under `--keep-going`.  @lsm5 @mtrmac WDYT?

**Comment by mtrmac** [comment]
Currently we actually only ignore+log invalid tags _if they are user-specified_: https://github.com/containers/skopeo/blob/7bbaffc4f461f49f903ca1351ced6ad247248e65/cmd/skopeo/sync.go#L335 .

Now I don’t quite think that is _right_, but in my mind it makes it very easy to argue that we should treat invalid tags coming from the registry no worse, i.e. ignore+log without any extra option. Invalid tags coming from the registry are conceptually the same kind of error, but it is clearly not the fault of the user running `skopeo sync`, and not something that could be trivially fixed by tweaking the `skopeo sync` invocation.

But I don’t really feel strongly about not aborting on these errors by default, vs. requiring the option.

---

(The digest-valued tags are either redundant, if they contain the right digest, or completely unusable, if they contain a different digest, because at the registry API level, “fetch this tag” and “fetch this `sha256:…` digest” look the same.)

**Comment by polobread** [comment]
In my case, we use skopeo sync multi docker repo and multi images to 10+ AWS accounts by CD pipeline periodical before 1 year ago.
After one day, we create new AWS account and add new account setting in CD pipeline. But we do not found any images in AWS ECR after auto skopeo sync. 
We troubleshooting 1 month and figure out 1 docker repo with a little invalid tags.
I think a little invalid tags are small warnings, it is unnecessary that break to sync the others valid tags images in automatically.
Thanks.
