### ISSUE TITLE
flat-dir copy target option

### ISSUE THREAD

**Issue by wrouesnel** [containers/skopeo#1751]
Skopeo has a number of filesystem related operations, but is notably missing a simple "extract an image and flatten all layers to a directory" option which would be very useful when inspecting the contents of images for non-container operations.

This issue is a request that an option for copying to and from simple flat directory structures be added.

**Comment by rhatdan** [comment]
Have you looked at `podman image mount`

**Comment by mtrmac** [comment]
Yes; the “flatten all layers to a directory” code is non-trivial (consider things like expressing different UIDs by unprivileged users) and I don’t think it exists in a trivial form. We have several implementations of that as c/storage graph drivers, along with the rest of Podman to set up everything needed to run c/storage + user namespaces etc. in that way.

Implementing some other graph-driver-unrelated code to flatten all layers would be quite a bit of code that would probably not be useful for any other purpose, with worries about keeping it in sync with the primary c/storage implementation.

---

WRT copying “from simple flat directory structures” into containers, that isn’t sufficient because a container image needs to have a config that allows running it. And creating images from directories + setting up config is exactly what Buildah, or `podman build`, is for.
