### ISSUE TITLE
Unable to build skopeo from source

### ISSUE THREAD

**Issue by snowmanstark** [containers/skopeo#1754]
I am trying to build skopeo from source in a centos7 machine but it keeps failing with the following error
```
[jenkins@centos7-builds-1jnxk skopeo]$ cd $GOPATH/src/github.com/containers/skopeo && make bin/skopeo
GO111MODULE=on go build -mod=vendor "-buildmode=pie" -ldflags '-X main.gitCommit=ca1b0f34d1d2c3e2074c9c231249f1a0e4d3ceb7 ' -gcflags "" -tags "   " -o bin/skopeo ./cmd/skopeo
# pkg-config --cflags  -- gpgme
Package gpgme was not found in the pkg-config search path.
Perhaps you should add the directory containing `gpgme.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gpgme' found
pkg-config: exit status 1
make: *** [Makefile:139: bin/skopeo] Error 2
[jenkins@centos7-builds-1jnxk skopeo]$
```
This occurs even if gpgme is installed 
```
Package gpgme-devel-1.3.2-5.el7.x86_64 already installed and latest version
Nothing to do
```

Can someone please guide me if I am missing something.

**Comment by mtrmac** [comment]
Thanks for your report.

I’m afraid centos7 is just too old/different for recent versions of Skopeo to build seamlessly. (Specifically, the `gpgme` package does not ship a `pkg-config` configuration; _and_ it requires a non-default library to be safe to use in Go.)

It would probably be easiest, by far, to use a centos7-targeted RPM shipping an older version of Skopeo.

Building a recent version (including a recent Go) is not something we test any more, and it’s quite likely to fail for several other reasons. Compare https://github.com/containers/skopeo/pull/1649 (incl. the gpgme minimum requirement), https://bugzilla.redhat.com/show_bug.cgi?id=1793083 , and there may be quite a few more gotchas I can’t immediately remember or gotchas we just didn’t run into because we are not testing that any more.

**Comment by snowmanstark** [comment]
Thanks @mtrmac
