### ISSUE TITLE
How to move images from one  aws ecr repo to another aws ecr repo using IAM role or credentials?

### ISSUE THREAD

**Issue by krishnaraman001** [containers/skopeo#1798]
Can someone please help me on how to copy images from one aws ecr  acount to another aws ecr account using IAM role or credentials?
How to configure them in skopeo?
How to create ECR repository with some set of policies using skopeo task if the ecr repo is not present?
Please provide some example or help me with a way?

**Comment by rittneje** [comment]
First install the ecr-credentials plugin. https://github.com/awslabs/amazon-ecr-credential-helper

Then configure your docker config (config.json) file like so:
```json
{
    "credHelpers": {
        "<account>.dkr.ecr.<region>.amazonaws.com": "ecr-login"
    }
}
```
Since you are dealing with two AWS accounts, you will need one entry for each.

Then you can run `skopeo copy` as usual.

If your two accounts require the use of separate users and/or roles, you will need to write some wrapper script around ecr-login in order to choose the correct profile. For example:

```bash
#!/bin/sh

AWS_PROFILE=<profile> docker-credential-ecr-login "$@"
```
That script must be executable, and must be in your PATH. The name of the script must start with "docker-credential-" and the entry in `credHelpers` must match the suffix. For example, if you name the script "docker-credential-abc", then the entry will be `"<account>.dkr.ecr.<region>.amazonaws.com": "abc"`. This is all described in the docker spec. https://docs.docker.com/engine/reference/commandline/login/#credential-helpers

**Comment by mtrmac** [comment]
Closing, please reopen if there’s more to be done.
