### ISSUE TITLE
Use of logrus causes incorrect use of stdout and stderr

### ISSUE THREAD

**Issue by juur** [containers/skopeo#1812]
Logrus appears to have an [unresolved ](https://github.com/sirupsen/logrus/issues/403)(and because logrus is in maintenance mode, will never be resolved) standard way of handling different logging levels going to stdout vs. stderr. As there is also no-way to set the log level and/or engage silent mode, this makes it hard to have fairly-silent scripts that only output on error.

It's not correct behaviour to redirect stdout to /dev/null and get INFO messages printed, really.

There are a few suggestions I can think of:

- Have two different loggers, one for stdout and one for stderr, and use the correct.
- Switch to a different Go logging framework that solves this problem
- Introduce a --log-level option and/or a --silent option to set the logging level to WARN

**Comment by mtrmac** [comment]
Thanks for the report.

A fairly large stack of dependencies uses `logrus`; so switching a framework wouldn’t be a simple Skopeo change, . It’s an option, in principle, but it’s a fairly hard sell — to my knowledge we don’t have a large set of issues that would motivate such a large-scale work.

For the same reason, having two different loggers isn‘t really possible.

The `--log-level` option has a precedent in Podman, so that seems the easiest way to handle this.
