### ISSUE TITLE
review/commit mechanics discussion

### ISSUE THREAD

**Issue by cgwalters** [containers/skopeo#1827]
In other GH organizations I work in (coreos/ and ostreedev/ namely) we enable the Github branch protection rule "Require pull request before merging" *and* "Require approval before merging".  IMO (and many other's) it should be thought of as a standard baseline that code that merges is reviewed by one other person.

I'm raising this issue becuase recently I was given administrator permissions in the containers/ GH organization (which I may ask to have removed) and that made the skopeo "merge button" turn green by default for me even before the code was reviewed.

I'd like to propose enabling the above flags here, so that merges require review (administrators can still bypass, but that's a distinct issue).

**Comment by mtrmac** [comment]
I think that’s how we usually works in practice (except for rare emergencies), just via social convention. Enforcing this via tooling seems like a good idea at a first glance.

**Comment by cgwalters** [comment]
OK cool, I've enabled those settings - this is easily changable later too of course.  One other thing I'm used to having enabling is the "auto merge" button - this will auto-merge a PR after it passes CI and the review requirements.  Are you OK enabling that too?

(These settings combined implement what other things like e.g. Prow do externally today via `/approve` and `/lgtm`)

**Comment by mtrmac** [comment]
I’m not immediately sure about that part…

One part is: I guess the set of conditions where I would feel comfortable with auto-merging is “the PR is on top of `main`, not behind; and that version was reviewed by a human; and that version passed tests” … but that might be unnecessarily strict or a human hitting the button (e.g. if there are 2 or 3 clearly unrelated pending PRs).

Personally, much more important to me is that I think it’s usually not worth it being an exception from the other container-runtimes repos; with most people working across the ≥ 5 repos, consistency seems valuable. Also, I definitely don’t understand enough about the available tooling and trade-offs. (Notably Prow is running on Podman and some of the other repos, and there was a tentative discussion of turning it on in the others.)

Let’s me defer to someone who actually understands these things… @cevich , is that something you can help with? Or if not, you know who would be the right person to discuss this?

**Comment by cgwalters** [comment]
Agreed consistency is important!  I noticed Prow wasn't on in this repo, that was my motivation here.  I had thought it was off in others but I admittedly don't watch many other repos here yet.  I'd definitely be fine addressing the consistency by going the Prow route - happy to help with that!

**Comment by mtrmac** [comment]
Also Cc: @vrothberg

**Comment by vrothberg** [comment]
Thanks for bringing that up, @cgwalters!

I like consistency and most projects under github.com/containers use a merge bot.  But I do not feel strongly about it; Skopeo has less traffic than Podman.

**Comment by cevich** [comment]
I'm also on the consistency band-wagon, from someone with admin access it makes spotting differences in our setups easier.

Tooling-wise w/ auto-merge: While on the surface it sounds like a simplification, it actually creates additional unintended complexities for us.  So I'm generally against it (but willing to listen/discuss) because there are multiple automation systems involved across many of our repos.  which:

a) Don't start or finish in sync with each-other.
b) Cannot easily be synchronized.
c) Consistency, it should be all-or-none to limit admin brain-drain.

---

> Require pull request before merging" and "Require approval before merging"

I'm okay with these assuming we set them consistently across all/most repos, and they don't interfere with release-branch creation (I don't think they would) - especially in podman.

@mheon during podman-releases, do you ever push straight to the new release branch or is there always a PR after branch-creation?  (I think there is, but want to check)

**Comment by mtrmac** [comment]
(_Aesthetically_, I’m not a fan of Prow managing the PR workflow. Writing text commands instead of pushing GUI buttons feels 1980s, and writing text commands into a human-targeted comment stream is a hack. But I’d rather make the process reliable and easy to use than aesthetically polished in this sense.

I’m also not sure that we use Prow for anything GitHub couldn’t do natively. Maybe Prow does its job so well that I don’t even notice all the things it’s doing :).)

**Comment by cgwalters** [comment]
> I’m also not sure that we use Prow for anything GitHub couldn’t do natively.

I think this is generally true, but note that the Github-integrated "auto merge" came long after Prow existed.  It's [a bit less than two years old](https://github.blog/changelog/2021-02-04-pull-request-auto-merge-is-now-generally-available/).

This all said, one thing Prow does too is PR "merge batching" with testing, which is a whole other level of complexity and sophistication; Github's equivalent is still in beta: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

**Comment by cevich** [comment]
Side note: I'm agree with Miloslav on the Aesthetics.  At one point I tried to convince other team members the green "review" button was superior to /commands.  I lost :cry:  COUGHdanwalshCOUGH :rofl: 

Yeah, I'll send a mail to the team about the review required box, and assuming they all agree I'll go through and click it everywhere.  Thanks for raising the issue Colin.

**Comment by TomSweeneyRedHat** [comment]
I don't have a strong opinion on either option, but would definitely vote for consistency, at least across our main repos, Podman, Buildah, Skopeo, Storage, Image, Netavark, etc.
