### ISSUE TITLE
skopeo-1.8.0-1.rhaos4.12.el8.x86_64  fails with `keyPath` in policy.json

### ISSUE THREAD

**Issue by jmarrero** [containers/skopeo#1846]
```
$ skopeo copy oci:/var/tmp/fcos oci:/var/tmp/test1
FATA[0000] Error loading trust policy: invalid policy in "/etc/containers/policy.json": Unknown key "keyPaths" 
```

```
$ skopeo copy oci:/var/tmp/fcos containers-storage:localhost/fcos
FATA[0000] Error loading trust policy: invalid policy in "/etc/containers/policy.json": Unknown key "keyPaths" 
```

```
$ skopeo inspect oci:/var/tmp/fcos
{
    "Digest": "sha256:c16aadb2d92c1fdbfdb57fb5fa8ae478c45b34ab888c765edee467a6d7260474",
    "RepoTags": [],
    "Created": null,
    "DockerVersion": "",
    "Labels": {
        "ostree.bootable": "true",
        "ostree.commit": "e6bd86f88bf4dea3c461fd250d9ba1bb6c835a83b6f3d17266d1296ad3ff58ef",
        "ostree.diffid": "sha256:28bfca2edff1e9c8037ff8e2e05ee1fb4bd14a296fb8125e3fe9629170a2e580",
        "ostree.linux": "4.18.0-425.3.1.el8.x86_64",
        "version": "412.86.202301111801-0"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:2d7573d1821f5759eedcb3bee40f7135c05496925fed6aa7a9be31a70833ad7e"
    ],
    "Env": null
}
```

However the Fedora version `skopeo-1.10.0-3.fc37.x86_64` has no trouble copying it. Any chance this is a known bug that can be backported?

**Comment by mtrmac** [comment]
Thanks for your report.

I don’t think this has anything to do with `oci:` every `skopeo copy` is going to fail like this.

`keyPaths` is a new feature in the `/etc/containers/policy.json` config file. Ideally, a RPM updating that config file should be paired with a corresponding Skopeo RPM that can process that config file.

Alternatively, OpenShift (which might be the target of the `rhaos4` builds) is supposed to own the `policy.json` configuration and AFAIK currently sets it up without `keyPaths`.

---

@jnovy PTAL, and speak up if I’m incorrect. Is there anything wrong about the modules? Do we ship an unexpected subset in some product?

---

We could, plausibly, backport the `keyPaths` feature to an older branch, but doing that here on GitHub would do nothing about an RPM from some stable source. (In particular, if this is a Red Hat shipped RPM, it would probably be better to report that using the right Red Hat product support channels / RPM bug tracking channels,  so that it can be tracked and potentially fixed correctly. But I’ll fully defer to @jnovy . )

---

A local workaround would be to replace `policy.json` with a configuration that does not use `keyPaths`, or to locally use `skopeo  --policy /some/other/policy.json copy …` (without changing the system-wide `/etc/containers/policy.json`)

**Comment by cgwalters** [comment]
This file comes from `containers-common`, so this is likely incorrect backporting there?

**Comment by mtrmac** [comment]
I’d guess a missing `Conflicts` — but really, the RPMs for `containers-common` and the software should arrive in the repo as a single update batch, in principle.

**Comment by jmarrero** [comment]
closing in favor of: https://bugzilla.redhat.com/show_bug.cgi?id=2162193
