### ISSUE TITLE
Replace golint with golangci-lint

### ISSUE THREAD

**Issue by mtrmac** [containers/skopeo#1892]
https://github.com/golang/lint says `golint` is deprecated and frozen; we are using `golangci-lint` in other repos, so we should move here as well.

Cc: @cevich :
- c/image’s `.cirrus.yml` says “# golangci-lint tool requires heavy cpu/memory or gets OOM'd”. Is that something to explicitly worry about here, or should we just try and see what happens?
- Looking at c/image, we are installing `golangci-lint` in `Makefile` on every test run. Would it pay off to include it in the CI image?

Note to self: After Skopeo migrates from `golint`, we should also remove the rules to install `golint` from c/image.

**Comment by cevich** [comment]
> Is that something to explicitly worry about here, or should we just try and see what happens?

Yes, especially if running it as a containerized-task in the cirrus community cluster.  If running it in a VM, it's much less of an issue.  Just be warned, you'll get very little help from golangci-lint when this happens.  It basically just does an `exit(125)` with no output.

> Would it pay off to include it in the CI image?

Yes, and we formerly did this for podman but it's since dropped out of my maintenance-ability - somebody moved ALL the tools under a repository directory, instead of `$GOPATH/bin`.

In any case, I think the old addage applies: Make it work, then make it "good", then optimize it :grin: 

Tip: Copy the golangci-lint config YAML from one of the other "working" repos. (podman or buildah).

Another option:  There's a gitlab-action for it (I think conmon uses it).  You could use that + a config file and not worry about touching the VMs.
