### ISSUE TITLE
Container catalog digest sha and skopeo digest sha are different

### ISSUE THREAD

**Issue by tmds** [containers/skopeo#1930]
According to the Red Hat Container catalog, the `6.0-22` tag of `registry.access.redhat.com/ubi8/dotnet-60` has a digest sha of `sha256:3e78917826ee54a981ee1d7122429d44457add74a12729d63ac9fa39fc499d4f`.

https://catalog.redhat.com/software/containers/ubi8/dotnet-60/6182efb9be25a74c00923849?tag=all&push_date=1670959740000 has:

![image](https://user-images.githubusercontent.com/1025424/221786538-802e0bdb-b740-45b7-93b7-4ce24a406bda.png)

For this tag, `skopeo` gives me a digest sha of `sha256:6edf5172867408b613090c211d12d50f39006ebfc885a217550cd1d683d7f666`.

```
$ skopeo inspect docker://registry.access.redhat.com/ubi8/dotnet-60:6.0-22
{
    "Name": "registry.access.redhat.com/ubi8/dotnet-60",
    "Digest": "sha256:6edf5172867408b613090c211d12d50f39006ebfc885a217550cd1d683d7f666",
    "RepoTags": [
...
```

Why are these shas different?

cc @mheon

**Comment by mtrmac** [comment]
Thanks for your report. I’m afraid this is confusing because the digests of different kinds of items look structurally the same.

The actual digest of the _multi-arch_ image is `6ed…`.

That _multi-arch_ image is a collection of individual _per-arch instances_ for x86_64, ARM64, and s390x; and `3e7…` is the digest of the x86_64 _per-arch instance_.

On the RH catalog, note the “Architecture” drop-down at the top, and see that the listed digest value changes with the chosen architecture.

Compare the multi-arch manifest list visible in `skopeo inspect --raw docker://…` ; you can pipe that to `sha256sum` or `shasum -a 256` (depending on your OS) to see the top-level digest, or to `python3 -mjson.tool` to get a more readable list of the individual architectures (which we should eventually make easier, #1283 ).

**Comment by tmds** [comment]
I'm glad you know what is causing the difference.

Is there a way to get the per-architecture sha from `skopeo`?

**Comment by mtrmac** [comment]
Right now, `inspect --raw … | $some_kind_of_json_parser`. #1283 should exist but doesn’t currently.
