### ISSUE TITLE
Copying saved docker-tar to Registry with Same Sha value as Source Registry

### ISSUE THREAD

**Issue by dnt238** [containers/skopeo#2222]
Hi,

Here is my use case:

I have a source Registry where I have say n number of images. I have tar files as well of those images. I want to copy the tar files of these images to Dest Registry however when I do so I see that SHA values on Source and Dest Registries are different. I want them same as my helm charts refer to images using SHA. I cannot do Registry->Registry copy for some internal reasons, I mandatorily have to use tar files.

Is this use case supported by Skopeo? If yes, how can I achieve same SHA as of Source Registry? Does manifest.json need to be altered or something else? Please advice.

**Comment by mtrmac** [comment]
Thanks for reaching out.

The `docker-archive` format simply doesn’t contain the relevant data to preserve the digest, and the data can’t be reconstructed. If you _have_ to use the `docker-archive` format (maybe because some scanner only supports that format), and you want to preserve original digests, I’m afraid you have no options at all.[1] (There’s another reason why this doesn’t work: `docker-archive` can not represent multi-architecture images, either.)

What I would generally recommend is a registry-to-registry copy to a temporary copy (e.g. running with a container), with the backend storage of that registry in a volume, and transferring that volume by tar. Alternatively, using the `dir:` transport, and transferring the individual directories by `tar`, would work (but potentially require more space because layers wouldn’t be shared across registries.

---

[1] A recent Docker update has started including OCI-formatted images inside `docker-archive` files. That is not currently supported by Skopeo, but anyway that would only work for images which are originally OCI, and that’s still fairly rare.

**Comment by dnt238** [comment]
Thanks for your response, here is what I did

1. mkdir reg_data
2. docker run -d -p 5000:5000 --restart=always --name registry -v ~/reg_data:/var/lib/registry registry:2
3. skopeo copy docker://my-src-registry/my-repo-image:my-tag docker://localhost:5000/image:test
4. docker image ls --digests and it shows same digest for src_registry as well as localhost one -- good
5. tar -czvf my-image.tar.gz ~/reg_data/docker/registry/v2/repositories/my-image-name
6. skopeo copy tarball:my-image.tar.gz docker://destination-registr/repo-image:test

Now I would expect this to carry forward the digest to the destination registry like you said but it did not, could you please help me on what I need to correct here?

**Comment by mtrmac** [comment]
- `tarball:my-image.tar.gz` is not the same thing at all. You need to also run a registry in the destination (the ~same `docker run` command), and do a registry-to-registry copy.
- Using `skopeo copy --preserve-digests` (possibly with `--all`) might not make a difference right now, but it would add certainty: the result is either an exact copy or an error message.

**Comment by dnt238** [comment]
Thanks a ton Miloslav!!
