### ISSUE TITLE
authentication required for ECR repo

### ISSUE THREAD

**Issue by sino1641** [containers/skopeo#2282]
Hi and thanks for your project. 
I am trying to use it for AWS ECR but cannot really log in.
First, AWS has a helper https://github.com/awslabs/amazon-ecr-credential-helper which means I just need to add one line `"credsStore": "ecr-login"` in docker config then I can download images from that private reg in docker cli. However, it fails in skopeo saying authentication required.
Also, I see from readme, login is needed so I tried `aws ecr get-login-password | skopeo login --username AWS --password-stdin URL` with response `Login Succeeded!`.
But skopeo inspect/copy is still falling with 
> FATA[0000] Error parsing image name "docker://ECR/repo": reading manifest latest in ECR/repo : unauthorized: authentication required

Kindly ask for some ideas on solving the issue? Thanks.

**Comment by mtrmac** [comment]
Thanks for reaching out.

`credsStore` is not currently implemented, primarily because the login state in `auth.json` does not survive reboot. That value can be configured in `credential-helpers` of https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md . Alternatively, use a per-registry entry with `credHelpers`.

Per other bug reports in the repo, `skopeo login` + `aws ecr get-login-password` does seem to, in principle, work; is it possible that the account really does not have access to the repo in question?

**Comment by sino1641** [comment]
Hi mtrmac,
Yes, the AWS credential is granted to access ECR/repos. I tried docker pull on the image successfully.
And as a workaround provided by the ecr helper github repo, I tried 
```json
"credHelpers": {
                "***.ecr.aws": "ecr-login"
        }
```
but still no luck.
Are there any other workarounds or debug options available? Thanks!

**Comment by mtrmac** [comment]
The `--debug` CLI option would show which files are actually being read. Beyond that, I don’t know.

**Comment by sino1641** [comment]
Hi and thanks again.
It works after I rebooted containerd.:)
