### ISSUE TITLE
When copying images to or from docker-archive or oci-archive, the reference information—specifically the registry, repository, and tag—is entirely lost.

### ISSUE THREAD

**Issue by JuryA** [containers/skopeo#2392]
**Type:** Bug
**Related To:** #854, #1878, #2023, #2370

---

## Description:

This issue underscores a persistent and frustrating problem encountered when copying images to or from docker-archive and oci-archive. The image reference data, which includes the registry, repository, and tag, is completely lost during the process.

This is not an isolated issue, as multiple related reports have highlighted the same problem. It is crucial to understand that this is not merely a minor inconvenience; it is a significant bug that affects workflows dependent on accurate image references.

Both Docker and Podman, when using their respective load and save commands, are capable of correctly storing and utilizing the registry, repository, and tag information. This functionality is essential, and its absence in the current tools is problematic.

Please address this issue with the urgency it warrants, as it impacts a wide range of use cases and can cause serious disruptions in development and deployment processes.

Thank you for the fix.

Note: I cannot provide additional information because I’m currently using a cell phone. However, since this issue is easily reproducible, I do not anticipate that to be a problem.

**Comment by mtrmac** [comment]
Thanks for your report.

It is very intentional that the sources and destinations are independent, because it allows full flexibility. There _must_ be some tool with that flexibility. So this is a feature, not a bug.

It’s, of course, possible to build some other tool with a more heuristic and less repetitive interface, easily a 3-line shell script invoking `skopeo copy`; or, in some cases, Podman provides a much more convenient interface. Users do have options.

---

Also, even if we _wanted_ to change the behavior, now we can’t do without possibly breaking existing scripts. That also points in the direction of building a tool (or, at best, a new Skopeo subcommand) on top of the generic functionality, not changing the existing behavior.

---

Now, I appreciate that users find that behavior surprising. We do document that, e.g.
> _source-image_ and _destination-image_ are interpreted completely independently; e.g. the destination name does not
automatically inherit any parts of the source name.

but it’s very possible that we should document it in some other places, or add more examples. Specific suggestions would be helpful.
