### ISSUE TITLE
Is there a way to cache the complete layers for copy work

### ISSUE THREAD

**Issue by cowcomic** [containers/skopeo#2419]
With a poor network the copy work often failed  A large image needs to download all the layers every time and it will fail every time.
I need a way to cache the downloaded layer so that I don’t have to download it again when I copy it again after failure.

**Comment by mtrmac** [comment]
Thanks for reaching out.

A `skopeo copy [--all --preserve-digests] docker://… dir:` will create a local copy, which can then be pushed elsewhere. But for that, the whole image download needs to succeed, because a write to `dir:` wipes the previous contents.

Alternatively, you can run a temporary registry on `localhost` (maybe in a container); that one does work a layer at a time, and on a failure, restarts the copy from the failed layer (from start).

In recent versions, downloads from registries have a limited resume logic, so _rare_ network interruptions of _specific kinds_ don’t terminate the whole layer operation. But uploads do need to happen whole layers at a time, so if an upload is interrupted, it can only be restarted from scratch.

**Comment by cowcomic** [comment]
OK，i will try to use registry as a hub

**Comment by mtrmac** [comment]
Please reopen if there are more questions.
