### ISSUE TITLE
adding --skip-existing flag to sync

### ISSUE THREAD

**Issue by marakomer** [containers/skopeo#2426]
We would like to use skopeo for registry syncing, but without support to skipping existing tags in the destination the amount of resulting docker pulls would be too large on a daily basis (our use-case is very simple - daily syncing of images from dockerhub repo to ghcr).

We have tried running it both in dry-run and without and dockerhub rate-limiting is choking it very quickly. Please let me know if there is already an existing work-around!

**Comment by mtrmac** [comment]
Thanks for reaching out.

The code is _already_  supposed to avoid syncing images that exist on the destination, based on manifest comparison — but that does require reading at least the manifests.

Removing even more accesses would require making an _assumption_, necessarily by user opt-in, that once a tag exists, it is never moved to a different image. And a single global tag is unlikely to be ideal for that, at least because the practice of having a `:latest` tag is _very_ widespread; so we would need a more complex option. That’s tracked in https://github.com/containers/skopeo/issues/1498 .
