### ISSUE TITLE
Stop vendoring master!

### ISSUE THREAD

**Issue by cyphar** [containers/skopeo#304]
Inside `vendor.conf` you have several projects that you are vendoring master from. While that might work in principle, I'm currently trying to backport `containers/image` patches and it's quite hard to figure out what version of `containers/image` is being used.

Please just stick to commit hashes!

**Comment by runcom** [comment]
let's do that, yeah

**Comment by cyphar** [comment]
:smile_cat:

**Comment by mtrmac** [comment]
I don’t care strongly either way, I can see that it would be useful. My only concern is that the `vendor.conf` should, as much as possible, clearly document whether we are _required_ to use precisely these commits (e.g. for the set of dependencies which we take from `docker/docker` and where we want to use exactly the same consistent versions) or whether we generally want to keep up with `master` and these commits are just a point-in-time snapshot which is perfectly fine to update.

**Comment by cyphar** [comment]
How about we add comments to `vendor.conf` what was checked out? The current system of adding everything in a commit message /sounds/ fine but I've run into several cases where the committer didn't write what commit was checked out.

**Comment by mtrmac** [comment]
> How about we add comments to `vendor.conf` what was checked out?

Are you suggesting
```
github.com/containers/image master # somecommitid
```
?

AFAICS the `vndr` output does not say which version was used, so I don’t know where the user would get that information in a race-free way. (Also, it’s not quite obvious that people who forget to write commit messages would not forget to update comments.) Manually checking each remote repo for tag mappings before running `vndr` would be way too much work, and eliminate about 50% of the value of an automated vendoring tool.

Other vendoring systems do understand the difference between the desired tag (which can move over time by itself) and the commit ID that was actually checked out (which is constant, and can be updated only explicitly); hopefully the golang ecosystem will mature.

**Comment by cyphar** [comment]
@mtrmac 

Yes, that's what I was suggesting. But as you say, it doesn't really work -- which is why we should not allow `master` to be used. I was just trying to work around your wish the "master semantically means any version". I disagree with the entire concept and I think it's blatantly dangerous (if it doesn't matter what version, then why are you vendoring it -- if you have to vendor something then you should be specifying _what_ you versioned).

> Manually checking each remote repo for tag mappings before running vndr would be way too much work, and eliminate about 50% of the value of an automated vendoring tool.

You could also use a tag if you want. The point is so that someone who wants to actually fucking use the information in `vendor.conf` doesn't have to spelunk the `git` history.

**Comment by cyphar** [comment]
> AFAICS the vndr output does not say which version was used, so I don’t know where the user would get that information in a race-free way

Also if we really wanted to go that way, we can make a PR to `vndr` to add the output -- that's not an issue.

**Comment by mtrmac** [comment]
> I was just trying to work around your wish the "master semantically means any version". I disagree with the entire concept and I think it's blatantly dangerous (if it doesn't matter what version, then why are you vendoring it -- if you have to vendor something then you should be specifying what you versioned).

To be clear, I want something like
```
github.com/containers/image somecommitid # this is intended to track master over time
github.com/docker/docker $TAG # This should track public stable releases over time
# This section containers dependencies of docker/docker; the comit IDs come from vendor.conf as of $TAG defined above. Both should be updated at the same time.
…

```
and so on.

---

As for “master semantically means any version”, (this is ~philosophy with no practical impact): Of course it does matter that we want a particular API shape, and a new enough release not to be buggy; the trouble is that we really can’t get both at the same time with _any_ of the options.

What we really want, and absolutely can’t get, is a Microsoft Windows-like “perpetual unchanging API” situation, where we have a minimal required version of the dependency, but we can use, and want to use, the latest possible version with all the bug fixes. (This is an ideal, even Windows breaks APIs from time to time, but they are fairly close.)

With dependencies breaking as they choose, we can either say “always follow master”, get all the bug fixes, but if they break the API, we will have to immediately adjust, or we can say “freeze on a commit”, get no API breakage, but also no bug fixes. _Either way_ there is an ongoing maintenance cost for this project, the only difference is that the API breakage cost is immediate, urgent, but easily visible and generally low-impact, but the lack of bugfixes cost is very easy to ignore, never urgent, but potentially catastrophic for security.

Both choices are pretty bad. I guess the ecosystem forces us to make a choice, and as I said above, I don’t really care strongly either way, so if you want the dependencies to be frozen until a human explicitly decides to update them, fine with me. All I am asking for is to make it very clear whether we are freezing on that particular commit for a special reason, or whether it is just a random point-in-time snapshot which _should_ be fairly regularly updated to get the latest bugfixes. I would hate for us to continue vendoring a single commit of a dependency for a decade, and for cargo-cult reasons never update that commit and possibly even worse spread the use of that decade-old commit into other projects just because nobody can remember any more why we decided on that particular commit.

**Comment by rhatdan** [comment]
I think this is fixed, closing.  Reopen if I am mistaken.

**Comment by mtrmac** [comment]
There are no longer any `master` references, but we have no record of which ones are frozen and which ones should be regularly updated.

With `go mod` looming, this will be revisited anyway.
