### ISSUE TITLE
New transport: archive-dir

### ISSUE THREAD

**Issue by runcom** [containers/skopeo#361]
The use case of this new transport would be to support consumers who need almost exactly what a registry has for a particular image (manifest and blob). We do currently have the `dir:` transport but: 1) we do not encourage its usage 2) it doesn't handle manifest conversion, if for instance, one always want docker v2s2 manifest.

With this new transport we want to leave to the user either the possibility to choose which manifest she wants (v2s1 vs v2s2) and choose if blobs are compressed or not.

This new transport will look similar to this (taken from share google doc):
```sh
# Possible archive-dir usage, with multiple manifests in $dir:
skopeo copy $source1 archive-dir:$dir/manifest1
skopeo copy $source1 archive-dir:$dir/manifest2
 
# Possible format of the directory:
 
$root/blobs/$digest
$root/$manifest[12]
$root/$manifest[12].mime-type
$root/version # contains “1.0”
 
#Shell script system to work-around limited archive-dir manifest management, if it were that limited:
skopeo copy $source1 archive-dir:$dir

mv $dir/manifest.json our-schema2-manifest
skopeo copy $source1 --schema schema1 archive-dir $dir # reuses blobs
mv $dir/manifest.json our-schema1-manifest 
```

@mtrmac @ipanova @mhrivnak PTAL

**Comment by mtrmac** [comment]
> With this new transport we want to leave to the user either the possibility to choose which manifest she wants (v2s1 vs v2s2) 

Should this be a property of the new _transport_, or just a completely independent option to `skopeo copy` / `copy.Image`? I was thinking the former (that would e.g. allow us to force using OCI formats for docker/distribution servers), but either would work. Admittedly a `skopeo copy` option would make it too easy to work around issues in the autodetection instead of fixing them. OTOH making the format an option of the transport requries us to think of a syntax (`archival-dir:/some/root/whatever@{schema1,schema2,oci}` ?)


As for the quoted CLI, note that that shows two different approaches (`$dir/$manifest_filename`, explicitly supporting multiple images in on directory vs. `$dir` with `manifest.json` and a shell script moving files around to be able to reuse the single directory even though that is unsupported.) Also this does not show choosing the manifest format at all.


Finally, as a bike-shedding point (feel free to ignore me), we might want to use the `dir:` name the “stable archival transport”, and rename the debugging-focused transport to `debug:`, to nudge users towards using the right one.

**Comment by mtrmac** [comment]
> and choose if blobs are compressed or not.

Does this need to be _optional_ (again, we would have to figure out a syntax), or can we just hard-code doing the compression?

**Comment by mhrivnak** [comment]
This would be a great and useful addition. Pulp is implementing support now for this speculatively. Our use case is:

1. User uses skopeo to create a local representation of a manifest and its blobs.
2. User uploads that representation to Pulp.

The main value to our users is the flexibility they get in step 1 to use a variety of different sources.

What are the next steps to getting this done?

**Comment by thomasmckay** [comment]
Bump on this? Having this working would allow progress on related aspects in foreman and Sat-6

**Comment by thomasmckay** [comment]
Still interested in this :)

**Comment by rhatdan** [comment]
@thomasmckay Probably best to ping on this in the New Year.  Most everyone is on break now.

**Comment by mtrmac** [comment]
https://github.com/containers/image/pull/377 / https://github.com/projectatomic/skopeo/pull/450:

- allows the user to force a specific manifest schema (independent of destination transport)
- allows making the blobs stored into `dir:` compressed
- adds a version number indication to the` dir:` format.

Contrary to the original description, there is currently not a separate `archive-dir:` transport, and the manifest MIME type is not explicitly recorded.

Is that sufficient for all the envisaged uses?

**Comment by mhrivnak** [comment]
Thanks! That matches what we discussed in the last design meeting and should be very useful. @ipanova can give further input on how that works out with Pulp and what additional behaviors may be valuable in the future.

**Comment by rhatdan** [comment]
@mhrivnak @mtrmac @vrothberg I think we are all set on this, so I am closing.  Reopen if I am mistaken.
