### ISSUE TITLE
skopeo should be able to return be the catalog from a docker-distribution based registry.

### ISSUE THREAD

**Issue by rhatdan** [containers/skopeo#364]
A User want to build tooling to keep multiple container registries in sync using skopeo.
In order to script this he needs to have a list of all container images at the source registry.  This is stored as a catalog and should be able to be retrieved using skope catalog command.

Add a new command catalog, which will bring back the entire registry catalog file in json format.

skopeo catalog docker:registry.access.redhat.com

Should output the catalog to stdout.

**Comment by mtrmac** [comment]
* This is necessary but not sufficient for full sync because it only lists repositories, not images in these repositories.  We would also need https://github.com/projectatomic/skopeo/issues/276 to list tags, and I don’t think there is any way to list untagged images (which are still accessible using the `@digest` notation).

* If this is supposed to be a generic command, we need to think about what the transport-independent semantics is (e.g. “what should `skopeo catalog dir:/usr` output?”). Perhaps we can avoid that and make a docker-specific hack for now, `skopeo docker-datalog $hostname` or something like that.

**Comment by so0k** [comment]
back to

```
curl -su $DOCKER_USERNAME:$DOCKER_PASSWORD https://$DOCKER_REGISTRY/v2/_catalog | jq .
curl -su $DOCKER_USERNAME:$DOCKER_PASSWORD https://$DOCKER_REGISTRY/v2/$IMAGE_NAME/tags/list | jq .
```
or in a single line (generate array of all images with their tags) using `curl`,`xargs` and `jq`:
```
curl -su $DOCKER_USERNAME:$DOCKER_PASSWORD https://$DOCKER_REGISTRY/v2/_catalog | jq -r .repositories[] | xargs -I'{}' curl -su $DOCKER_USERNAME:$DOCKER_PASSWORD https://$DOCKER_REGISTRY/v2/{}/tags/list | jq --slurp .
```

**Comment by rhatdan** [comment]
@mtrmac @vrothberg Is this something we should pursue?  Should we look at interns working on this?  Do you think it is important?

**Comment by vrothberg** [comment]
I am taking a shot and close it in favor of the skopeo-sync PR https://github.com/containers/skopeo/pull/524.

**Comment by mtrmac** [comment]
`skopeo sync` won’t use the catalog to list all repositories.

The existing `podman search` can be used for this, e.g. `podman search registry.fedoraproject.org/` (but that registry reasonably limits the number of results, so it is only marginally useful.)

Considering that a sane registry server rarely support returning the full catalog, and that none of this can deal with untagged images, yes, let’s close.
