### ISSUE TITLE
Add atomic transport type to standalone-sign

### ISSUE THREAD

**Issue by aweiteka** [containers/skopeo#373]
We need to support an existing image in OpenShift (atomic transport type).

I would expect something like this, where `--output` arg becomes optional if `--atomic` is provided:

```
$ skopeo standalone-sign <manifest> <docker-reference> <key-fingerprint> [--output|-o signature][--atomic]

--atomic Write signature to OpenShift API
```

**Comment by mtrmac** [comment]
Not `--atomic`, the user should specify a _transport_`:`_name_` so that we don’t need to add an extra set of transport-specific options , and because it’s not in general possible to go from _docker-reference_ to an image location.

How about
```
skopeo add-signature $transport:$name $manifest $signature-blob
```
, separating the “create signature” and “write it somewhere” steps? That would allow using `standalone-sign` used in an isolated signing server without access to registries, and `add-signature` in a client to the signing server.

In terms of `containers/image`, this wouild probably be an `ImageDestination.AddOneSignature(manifestBlob []byte, signature []byte)`, which can be used as a single call as an alternative to the currently required `PutBlob`*,`PutManifest`,`PutSignatures`,`Commit` sequence.

**Comment by aweiteka** [comment]
> skopeo add-signature $transport:$name $manifest $signature-blob
> 
> , separating the “create signature” and “write it somewhere” steps?

Sounds good.

**Comment by rhatdan** [comment]
I believe this is fixed and we no longer want to support atomic, so I am closing.  Please reopen if this is not correct.

**Comment by mtrmac** [comment]
Nothing like this actually exists (apart from dubious `skopeo copy --sign-by `_keyID_` docker://`_location_` docker://`_location_`) — but
1. the `atomic:` transport is deprecated
2. such a workflow implies absolute trust in the registry, while the signatures basically exist to remove the need for such trust; images should primarily be signed when moving from a (necessarily) trusted environment (e.g. the build machine) to a less-trusted destination. That’s not to say that this could _never_ be useful, but there’s hight risk of misuse if users don’t consider the trust implications; so I’m not inclined to make this very easy.
