### ISSUE TITLE
OCI image transport broken again?

### ISSUE THREAD

**Issue by cyphar** [containers/skopeo#455]
Hi, it looks like the semi-recent `:`-related changes have broken the OCI transport completely:

```
% skopeo copy docker://ubuntu oci:ubuntu
FATA[0000] Invalid destination name oci:ubuntu: Invalid OCI reference ubuntu:: path /home/cyphar/build/obs/home:cyphar:containers:skopeo_v0.1.26/skopeo/ubuntu contains a colon 
% skopeo copy docker://ubuntu oci:ubuntu:latest
FATA[0000] Invalid destination name oci:ubuntu:latest: Invalid OCI reference ubuntu:latest: path /home/cyphar/build/obs/home:cyphar:containers:skopeo_v0.1.26/skopeo/ubuntu contains a colon
```

You'll note that both `oci:ubuntu` (which shouldn't work anymore) and `oci:ubuntu:latest` are both broken. This happens on `0.1.26`.

**Comment by cyphar** [comment]
Eugh, I just figured out it's because we calculate the absolute path rather than using the relative one. That doesn't seem necessary (not to mention I think our current handling of `:` is broken -- because it arbitrarily disallows paths containing `:`).

**Comment by mtrmac** [comment]
Yeah, we refuse absolute paths in `:` in them, originally because for such names `PolicyConfigurationIdentity` and `PolicyConfigurationNamespaces` can be ambiguous. So, I don’t think this has ever worked, or if it has, it wasn’t intended to.

Actually the absolute path as used for `PolicyConfiguration*` no longer treats `:` specially (see also https://github.com/containers/image/pull/379/files). OTOH `StringWithinTransport`/`ParseReference` _does_ treat `:` specially, so maybe we could allow relative paths which don’t contain colons, even if the absolute path does.

**Comment by rhatdan** [comment]
@cyphar @mtrmac @vrothberg Is this still an issue?

**Comment by vrothberg** [comment]
Already fixed, closing.
