### ISSUE TITLE
Run Travis tests also in CentOS

### ISSUE THREAD

**Issue by mtrmac** [containers/skopeo#47]
… to detect build breakage before we merge to `master`.

I got as far as #46 , but finishing it would require more time than I can spare right now.

**Comment by mtrmac** [comment]
(Is there anyone maintaining a canonical version of all this infrastructure? skopeo must be like the thousandth project with similar needs, reinventing this just for skopeo seems such a waste.)

**Comment by cgwalters** [comment]
I am planning to work on doing PR testing building on top of https://ci.centos.org/job/atomic-rdgo-centos7/

**Comment by rhatdan** [comment]
@mtrmac @vrothberg What is the state of this?  Should we ask QE For help?

**Comment by mtrmac** [comment]
I would hope that this gets addressed along with the conversation about using Travis CI in general, and maybe consolidating the CI designs across containers/*. Any help would of course be welcome.

(Really the biggest win for skopeo CI would be not building the OpenShift binary on every CI run.)

(I can’t remember any instance of CentOS-specific breakage since #45 , so this is not all that urgent.)

**Comment by cevich** [comment]
Suggestion: This issue can probably be closed.  CentOS Streams might be a good target, but even that is so far downstream it's probably better to rely on the rpm/dist-git based system-testing (assuming that's happening).  To be clear, my experience is based on attempting RHEL and CentOS testing early on, for upstream podman CI.  I found it to be an extraordinarily difficult maintenance burden.  Since bleeding-edge dependencies constantly need to be grafted into an "old" distro. not designed for them.

**Comment by vrothberg** [comment]
SGTM
