### ISSUE TITLE
Minimum go version: Informative error message on build

### ISSUE THREAD

**Issue by taqtiqa-mark** [containers/skopeo#492]
Part of the Travis-CI.org (trusty) build using go 1.2 (updated)

Complete build [log here](https://travis-ci.org/taqtiqa-admin/rkt-stacks/jobs/364119324#L805)
Partial log output
````bash
Setting up golang (2:1.2.1-2ubuntu1) ...
Cloning into '/home/travis/gopath/src/github.com/projectatomic/skopeo'...
go build "-buildmode=pie" -ldflags "-X main.gitCommit=28080c8d5f7ac21434948601639ab26ab7aa40bb" -gcflags "" -tags "btrfs_noversion libdm_no_deferred_remove " -o skopeo ./cmd/skopeo
flag provided but not defined: -buildmode
````

**Comment by mtrmac** [comment]
Are you sure this build is using 1.9?

> Setting up golang (2:**1.2.1**-2ubuntu1) ...

1.2.1 would be _really_ old, definitely older than anything we’ve ever used with skopeo.

`-buildmode=pie` does exist in 1.9: https://go.googlesource.com/go/+/go1.9.5/src/cmd/go/internal/work/build.go#267 .

**Comment by taqtiqa-mark** [comment]
Hmm, let me check.  Stand by.

**Comment by rhatdan** [comment]
@taqtiqa-mark @mtrmac @vrothberg Is this still and issue?  Can we close it?

**Comment by vrothberg** [comment]
I understand the motivation for the request but think that go is really hard to get started with in general. By default, the Makefile builds skopeo in a container which I hope reduces the burden from new users.

**Comment by mtrmac** [comment]
> By default, the Makefile builds skopeo in a container which I hope reduces the burden from new users.

Only if that container happens to exactly match your system (in which case there’s little benefit to the container); otherwise it creates a binary that is dynamically-linked and not even all that likely to work.

Version enforcement is traditionally done something like `autoconf`, or some other build system. We almost certainly don’t want that amount of complexity right now.

Adding an extra version check into the `Makefile` manually would work, and be easy enough to do once, but also be pretty likely to be overlooked and not updates when the code actually starts requiring a newer version; so we would, I guess, want to somehow connect the version check with the Go versions used by CI, and that’s starting to look a bit too much work to be worth it.

The traditional answer, of course, is to delegate all of this to a Linux distribution 😈
