### ISSUE TITLE
skopeo declares source or destination invalid when FQDN ends in .

### ISSUE THREAD

**Issue by lbrigmanArris** [containers/skopeo#544]
When trying to run the copy command using a FDQN where the last character is a period
 skopeo declares:
FATA[0000] Invalid destination name docker://docker-registry.default.svc.cluster.local.:5000/gsm/mdc-ui:latest: invalid reference format

This is using:
skopeo --version
skopeo version 0.1.31-dev

In OpenShift, this is the value returned from a lookup on the service.

**Comment by rhatdan** [comment]
Do you think the DFQN ending with a period is valid?

**Comment by lbrigmanArris** [comment]
Yes, I think it is.
Here is the use case:
oc project default
Now using project "default" on server "https://gsm-t1.lab.c-cor.com:8443".
[root@gsm-t1 ~]# oc get svc
NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
docker-registry    ClusterIP   172.30.211.188   <none>        5000/TCP                  14d
kubernetes         ClusterIP   172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     14d
registry-console   ClusterIP   172.30.132.64    <none>        9000/TCP                  14d
router             ClusterIP   172.30.201.13    <none>        80/TCP,443/TCP,1936/TCP   14d
[root@gsm-t1 ~]# host 172.30.211.188
188.211.30.172.in-addr.arpa domain name pointer docker-registry.default.svc.cluster.local.

Instead of needing to do those steps every time in automation, replacing it with the returned name will be valid for any OpenShift cluster that has the docker-registry running.

**Comment by rhatdan** [comment]
@mtrmac WDYT

**Comment by mtrmac** [comment]
> Do you think the DFQN ending with a period is valid?

No.

docker/distribution references are not arbitrary strings, and have restricted syntax.  Refusing the trailing `.` in DNS names is, in this respect, no different from refusing non-ASCII or uppercase characters. Just because DNS has syntaxes which accept them does not mean docker/distribution references must accept them a well.

Also consider what accepting other forms does to comparisons and lookups (for the “block registry” list, for example).  Sure, c/image/docker/reference could canonicalize the format on input, and it would probably _mostly_ work, but even then it would require a detailed audit of c/image to make sure that there are no other parsers hard-coding expectations about the structure, and doing this _correctly_ over libpod/buildah would be very non-trivial amount of work for little benefit.


> Instead of needing to do those steps every time in automation, replacing it with the returned name will be valid for any OpenShift cluster that has the docker-registry running.

This seems to miss some context; what “those steps”, in what “automation”, replacing which “it” in what “returned name”?

If you are saying that you need to do some `host $(oc get svc | awk …` to get an IP address, and then convert it into a host name to use for `skopeo`, and that accepting the trailing `.` would make your job easier,

1. To me, (someone with not that much practical experience with OpenShift, to be fair), that seems entirely backwards; a _major reason_ for using DNS names is that they should be longer-lived/more stable than IP addresses; shouldn’t OpenShift (via a `route` object, or something like that) be maintaining a stable DNS name which can be used without looking up IP addresses at all? (In fact `docker-registry.default.svc.cluster.local` looks suspiciously like such a stable DNS name.) In general, the pods running the service can be reassigned to a different node at any time, after all.

1. Also, HTTP in principle supports multiple hostnames  served from a single IP address, so _in general_ the IP→DNS lookup is not even guaranteed to get you the right service running on that IP address (though it may be fine for that specific OpenShift service, I wouldn’t know).

2. Even if you _had_ to write such a shell script for some reason, that shell script already must parse _ip-address_`.in-addr.arpa domain name pointer `_hostname_`.`, so stripping the trailing dot seems like a very trivial adjustment.

> Also docker client accepts it as valid.

It doesn’t AFAICS:
```console
$ docker pull docker-registry.default.svc.cluster.local.:5000/gsm/mdc-ui:latest
Error parsing reference: "docker-registry.default.svc.cluster.local.:5000/gsm/mdc-ui:latest" is not a valid repository/tag: invalid reference format
[mitr@f28 ~]$ rpm -q docker
docker-1.13.1-61.git9cb56fd.fc28.x86_64
```
and the github.com/docker/distribution/reference parser has not notably changed upstream since 1.13 either, to my knowledge

**Comment by rhatdan** [comment]
This should have been closed a long time ago.
