### ISSUE TITLE
Signature verification against the same images aross different registry.

### ISSUE THREAD

**Issue by smekkley** [containers/skopeo#792]
Is it plausible for skopeo sign verification to return ok, when the image is signed by the same gpg key regardless of registry original domain?
The use case for this is where you have docker registry replicated across locations, but pushing and signing happens on the only one master registry.

**Comment by mtrmac** [comment]
For that case, I would recommend configuring the replicated registries as mirrors in https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md (with this configuration possibly different at each location, to point at the local mirror); if configured that way, applications can continue to refer to the original image location (i.e. don’t have to be updated to run in a different location), and signatures continue to enforce the expected image identities.

(Alternatively, `policy.json` can be set up to expect the original registry when using registries on the mirrors, but that’s currently more cumbersome. There is no way to verify the signature was made by a specific key but ignoring the identity; using signatures that way is frequently a mistake because it allows an attacker to substitute images, e.g. causing the client to use an old vulnerable image instead of the desired updated version)

**Comment by smekkley** [comment]
Thanks for the suggestion.
Is it correct that if I have a configuration like the following, access to `rw.com` with skopeo/podman/buildah should connect to `ro.com`? Because it doesn't work. It always try to connect to `rw.com`. If `rw.com` is down, it doesn't work naturally. 
```
[[registry]]
prefix = "rw.com"
location = "ro.com"
```

**Comment by smekkley** [comment]
After podman system prune --all, it started working.
But signature verification stops working because it is configured to check for the original domain. If I set the configuration to the mirror registry, signature verification fails because the image is signed for the original domain and the signature verification still expects the original domain.

I am curious why is it a bad practice to ignore the domain in case of docker? Doesn't the attacker still need a gpg private key? Doesn't rpm signature only check for gpg?

**Comment by smekkley** [comment]
Probably I have to re-sign the images with alias configured. I'll update here once I confirmed it. I think this is a good workaround.

**Comment by mtrmac** [comment]
> But signature verification stops working because it is configured to check for the original domain. If I set the configuration to the mirror registry, signature verification fails because the image is signed for the original domain and the signature verification still expects the original domain.

Yes, that’s the way it was designed. The signature expresses “what the image is”, not “where it is located”.  “pull `foo`” expresses the intent of the user to use `foo`, so the signature should say `foo` (regardless of the IP address, host name, whether the physical storage is local or on some cloud service). And conversely, it should be possible to mirror images signed by a supplier without having to ask the supplier to also sign the images for the mirror locations.

> I am curious why is it a bad practice to ignore the domain in case of docker? Doesn't the attacker still need a gpg private key? Doesn't rpm signature only check for gpg?

If, as is the typical case, the signer has a single GPG private key, or the same set, for many products, or uses it over many years, only checking the right GPG private key would allow an attacker to substitute a completely different image (e.g. a wide-open debugging-only NFS server instead of a very-restricted authentication service that must not disclose credentials), or an old known-vulnerable v0.0.1 image instead of the latest version with all known vulnerabilities fixed.

**Comment by mtrmac** [comment]
There will eventually be https://github.com/containers/image/issues/884 as an alternative; but otherwise this is working as designed.
