### ISSUE TITLE
Deleting by tag unexpectedly deletes image and entire references

### ISSUE THREAD

**Issue by scrwr** [containers/skopeo#795]
While I'm aware, that the registry API doesn't support deleting tags only, skopeo should not proceed the deletion of the entire image without a clear warning if more references exist.

The problem arises from the fact, that skopeo translate the request for deleting an tag to a deletion of the digest and hence all tags referring to it. This is unexpected for the standard user. Even the documentation doesn't warn about it.

I'd recommend to check, whether there are more references to the image about to delete and request for force deletion to ensure, user is aware of the impact.

**Comment by vrothberg** [comment]
Thanks for opening the issue! I have mixed feelings about changing the behavior as some users might rely on the current behavior. We could add an additional flag to not delete the image if it has more than one tag.

@mtrmac @rhatdan WDYT?

**Comment by mtrmac** [comment]
Thanks for raising this.

In principle, I’m tempted to either require digests for the delete operation (but no longer accepting tags would be an ABI break), or to make this a RFE for the docker/distribution protocol to provide more primitives to allow making this reliable and user-friendly (which might be difficult with the general stateless design, and not necessarily more efficient given the way docker/distribution servers record tags). Neither is all that attractive or even necessarily productive short-term.

> We could add an additional flag to not delete the image if it has more than one tag.

That’s kind of awkward because there isn’t a get-tags-by-digest operation, so we would have to list all digests and then download all tagged manifests to see if there is a match; possible in principle, sure, but it could be very expensive. (BTW the “delete image by digest” operation internally has to do a similar expensive linear search as well, if I read https://github.com/docker/distribution/blob/a8371794149d1d95f1e846744b05c87f2f825e5a/registry/storage/tagstore.go#L144 correctly.)

Also, would that be a flag in the c/image API or only a Skopeo convenience? I guess the latter.

**Comment by scrwr** [comment]
I guess RFE is the right way. Especially as the behaviour is inconsistent between local docker rmi handling and docker-registry. docker rmi removes just the tag and only deletes the digest, when the last tag is deleted. I would expect the exact same behaviour in docker-registry.

**Comment by irispenker** [comment]
Hi
I am running Skopeo from a container .
Managed to copy images from one registry to another, which is AWS ECR, no need to special configuration .
Now i am trying to delete an image from same ECR, and i get same errors.
I tried deleting with digest and is says my user name password is wrong , same user can simply delete the image from elsewhere.

Can someone help by saying :

1)Should i have some registry yml configuration set for my ecr just for delete ?

2)If so - where should it be located ? so many different locations are mentioned in different posts :
According to https://github.com/containers/skopeo/blob/master/docs/skopeo.1.md#skopeo-delete
config should be here : /etc/containers/storage.conf
But according to https://docs.docker.com/registry/configuration/#delete
Docker is expecting in other location.
And the above mention : /etc/docker-distribution/registry/config.yml
What should it be ???

3)If i do need this file , how should it look like for AWS ECR ??

I must mention that i am not using docker directly within the container - only Skopeo.
So if you go to my container and type docker command it will error that "docker not found" .

Can someone help ?

**Comment by rhatdan** [comment]
@vrothberg @mtrmac @scrwr I don't believe anything ever happened with this.  Was a RFE ever opened with Docker distribution?

**Comment by rhatdan** [comment]
Since this involves changes to the Docker distribution, I don't see Skopeo being able to effect change.  I am going to close this issue.  If The registry API ever supports this, then we will get containers/image and skopeo to work with the standard.
