### ISSUE TITLE
Sync: Add option to keep full name on target

### ISSUE THREAD

**Issue by PhilippHomann** [containers/skopeo#854]
Hi,

I'm trying to sync images between two docker registries using skopeo.

**Current behavior**
Without `--scoped` a source image `registry1/first/last:tag` results in `registry2/registry1/first/last:tag`.
With `--scoped` a source image `registry1/first/last:tag` results in `registry2/last:tag`.

**Wanted behavior**
With `--whatever` a source image `registry1/first/last:tag` results in `registry2/first/last:tag`.

My current workaround/patch to do this with `--scoped`:
```
diff --git a/cmd/skopeo/sync.go b/cmd/skopeo/sync.go
index 93f6a362..f0bc9b86 100644
--- a/cmd/skopeo/sync.go
+++ b/cmd/skopeo/sync.go
@@ -512,7 +512,11 @@ func (opts *syncOptions) run(args []string, stdout io.Writer) error {
                        switch ref.Transport() {
                        case docker.Transport:
                                // docker -> dir or docker -> docker
-                               destSuffix = ref.DockerReference().String()
+                               removeRegistry:= func(s string) string {
+                                       split := strings.Split(s, "/")
+                                       return strings.Join(split[1:], "/")
+                               }
+                               destSuffix = removeRegistry(ref.DockerReference().String())
                        case directory.Transport:
                                // dir -> docker (we don't allow `dir` -> `dir` sync operations)
                                destSuffix = strings.TrimPrefix(ref.StringWithinTransport(), srcRepo.DirBasePath)
```
What do you think?

**Comment by rhatdan** [comment]
@vrothberg @mtrmac WDYT?

**Comment by mtrmac** [comment]
I acknowledge the need to create that particular repo structure, sure.

As for the interface, I’m in general not thrilled about adding various magic string editing options; that will never satisfy everyone.

A command syncing a single repo can just have the destination option changed directly, can’t it? The same for series of commands generated by software from some kind of a list.

So, is this necessary only for `--src yaml`? And if so, would it work just as well to allow specifying the destination in  the same `yaml` file, instead of the current sources-in-yaml → destinations-decided-by-magic options where we are tempted to keep adding options to tune the magic?

**Comment by PhilippHomann** [comment]
Better question would be if this is expected behavior.
I understand the use-case for using `--scoped`.
But removing parts of the image name when not using `--scoped` seems like a bug to me.
Don't see a reason to use only the last part and strip off everything else.

**Comment by okimiko** [comment]
> So, is this necessary only for `--src yaml`? And if so, would it work just as well to allow specifying the destination in the same `yaml` file, instead of the current sources-in-yaml → destinations-decided-by-magic options where we are tempted to keep adding options to tune the magic?

The only thing, which should be possible is to keep the image name including its path without any extensions so that it is possible to pull the image from the source and destination registry without changing anything else but the registry: Basically a `--scoped-without-registry` option or a mode for scoped. In my opinion there is no need to implement this in the yaml file.

The current implementation nearly caused me to throw away skopeo and use my creepy docker pull / tag / push script again ...

**Comment by mtrmac** [comment]
> Better question would be if this is expected behavior.
> I understand the use-case for using `--scoped`.
> But removing parts of the image name when not using `--scoped` seems like a bug to me.
> Don't see a reason to use only the last part and strip off everything else.

To be fair, the man page is not entirely explicit about whether namespaces are used in non-`scoped` calls.

But, pragmatically: this is what the original PR did and now it’s in a release. Changing the behavior could break existing users, so I’m very reluctant to do that. 

---

The way I look at it, does it _matter_? Right now, with `--scoped`,
```sh
skopeo sync --src docker --dest docker --scoped docker.io/library/alpine registry2.example
```
writes to `registry2.example/docker.io/library/alpine:…`
and non-`scoped`
```sh
skopeo sync --src docker --dest docker docker.io/library/alpine registry2.example
```
writes to `registry2.example/alpine:…`.

If you want `--whatever` to write to `registry2.example/library/alpine:…`, a new `--whatever` is _not necessary_; you can already do
```
skopeo sync --src docker --dest docker docker.io/library/alpine registry2.example/library
```

---

So, I don’t quite understand
>  In my opinion there is no need to implement this in the yaml file.

AFAICT the _only_ users who need a new `--whatever` are users using the YAML format, because non-YAML users can just adjust the destination on the command line. Isn’t that right?

So, we are basically only talking about how to extend the YAML use case, aren’t we?

Cc: @flavio

**Comment by PhilippHomann** [comment]
> skopeo sync --src docker --dest docker docker.io/library/alpine registry2.example/library
Okay you are right. Didn't knew that this one works.
Maybe it would be worth putting this example to the doc...

> So, we are basically only talking about how to extend the YAML use case, aren’t we?
Seems so..

**Comment by rhatdan** [comment]
@PhilippHomann Open a PR to change the docs to meet your expectations, please.

**Comment by PhilippHomann** [comment]
@rhatdan Done: see #870

**Comment by rhatdan** [comment]
@PhilippHomann Awesome, thanks.

**Comment by art-shutter** [comment]
Sorry to reopen the thread, but it seems that I am looking for exactly the `--whatever` flag referred to here for my yaml.
Without yaml functionality to let original registry name be omitted with `--scoped`, I have to resort to calling skopeo in loop, which is slower ans inconvenient
