### ISSUE TITLE
inspect: different digests for the same docker and docker-archive image

### ISSUE THREAD

**Issue by misuzu** [containers/skopeo#949]
Take a look at `Digest` and `Layers` fields: they are different for the same image.
Is this normal behavior? I would like to check `Digest` fields to ensure that image on registry is up to date to avoid pushing when not needed.
```bash
$ skopeo copy --insecure-policy docker://alpine:latest docker-archive:alpine.tar
Getting image source signatures
Copying blob df20fa9351a1 done
Copying config a24bb40132 done
Writing manifest to image destination
Storing signatures
$ skopeo inspect docker-archive:alpine.tar
{
    "Digest": "sha256:0fe895ba713b184489c17550d67464dd67fade3f92f3f0c1904dc8df6750d609",
    "RepoTags": [],
    "Created": "2020-05-29T21:19:46.363518345Z",
    "DockerVersion": "18.09.7",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:50644c29ef5a27c9a40c393a73ece2479de78325cae7d762ef3cdc19bf42dd0a"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]
}
$ skopeo inspect docker://alpine:latest
{
    "Name": "docker.io/library/alpine",
    "Digest": "sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321",
    "RepoTags": [
        "2.6",
        "2.7",
        "20190228",
        "20190408",
        "20190508",
        "20190707",
        "20190809",
        "20190925",
        "20191114",
        "20191219",
        "20200122",
        "20200319",
        "20200428",
        "3.1",
        "3.10.0",
        "3.10.1",
        "3.10.2",
        "3.10.3",
        "3.10.4",
        "3.10.5",
        "3.10",
        "3.11.0",
        "3.11.2",
        "3.11.3",
        "3.11.5",
        "3.11.6",
        "3.11",
        "3.12.0",
        "3.12",
        "3.2",
        "3.3",
        "3.4",
        "3.5",
        "3.6.5",
        "3.6",
        "3.7.3",
        "3.7",
        "3.8.4",
        "3.8.5",
        "3.8",
        "3.9.2",
        "3.9.3",
        "3.9.4",
        "3.9.5",
        "3.9.6",
        "3.9",
        "3",
        "edge",
        "latest"
    ],
    "Created": "2020-05-29T21:19:46.363518345Z",
    "DockerVersion": "18.09.7",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:df20fa9351a15782c64e6dddb2d4a6f50bf6d3688060a34c4014b0d9a752eb4c"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]
}
```

**Comment by misuzu** [comment]
With `--raw` i get what i need. Weird.
This code is working as expected:
```bash
path_digest=$(skopeo inspect docker-archive:$path --raw | jq -rM '.config.digest')
remote_digest=$(skopeo inspect docker://$remote --raw 2> /dev/null | jq -rM '.config.digest')

if [ "$path_digest" == "$remote_digest" ]; then
  echo "Up-to-date $remote"
else
  echo "Pushing $remote"
  skopeo copy -q --insecure-policy docker-archive:$path docker://$remote
  echo "Pushing $remote success"
fi
```
Is there a reason `skopeo` does not have this feature? This would speed up things significantly.

**Comment by mtrmac** [comment]
> Take a look at `Digest` and `Layers` fields: they are different for the same image.
> Is this normal behavior?

Yes. The manifest digest and layer blob digests are artifacts of the _representation_ of the image, and `docker://` and `docker-archive:` use different representations. (In this particular case, layers in `docker://` are typically compressed and layers in `docker-archive:` are uncompressed; and the `docker-archive:` format does not even _have_ a manifest, so the value reported by `skopeo inspect` as a manifest digest is an entirely artificial outcome of how `docker-archive:` is implemented).

> I would like to check `Digest` fields to ensure that image on registry is up to date to avoid pushing when not needed.

My primary recommendation would be not to use `docker-archive:`; it is quite slow both to create and access. Ideally, just use a docker/distribution registry server.

That said, I would expect a repeated `skopeo copy docker-archive:… docker:…` to be quite fast, basically a metadata check (+ a cheap upload of config+manifest), as long as the blob info cache is persisted between the two invocations. So doing a manual check should not be necessary unless you really need to know whether the image has already been uploaded.


> With `--raw` i get what i need. Weird.

It’s not really `--raw`, it’s that you are now comparing the config digest instead of the manifest digest. Sure, that will work, except that schema1 images don’t _have_ a config digest.

> Is there a reason `skopeo` does not have this feature?

I guess you could use `skopeo inspect --config --raw …` to read the configs, and compare them. But…

> This would speed up things significantly.

… I’d recommend to (not use `docker-archive:` at all, if you can help it, and) just use `skopeo copy` and let it detect pre-existing blobs.

**Comment by misuzu** [comment]
> My primary recommendation would be not to use `docker-archive:`; it is quite slow both to create and access. Ideally, just use a docker/distribution registry server.

I'm using `nix` to build `tar` images so docker is not involved at all and `docker load` + `docker push` is much slower than `skopeo copy`. Doing `skopeo inspect` on local and remote image is faster than just `skopeo copy` when image is already up-to-date, but if it isn't - extra unpack is required (`inspect` and then `copy`) which is not that great.

My issue is solved via `--raw` command argument so i'm closing this.

**Comment by rhatdan** [comment]
@misuzu if you wanted to write a quick blog about using Skopeo over using Docker, that would be appreciated...
